// ui.lang.js
(function () {
  const LANG_KEY = 'gdmm_lang';

  const translations = {
    en: {
      'ui.NewMarkerTitle': 'New marker',
      'ui.GeneralMarker': 'Personal spot',
      'ui.QuestMarker': 'Quest',
      'ui.BossMarker': 'Boss',
      'ui.LootMarker': 'Loot',
      'ui.WaypointMarker': 'Passage',
      'ui.DonjonMarker': 'Donjon',
      'ui.NPCMarker': 'NPC',
      'ui.ToolsTitle': 'Tools',
      'ui.RoutesList': 'Routes list',
      'ui.MarkerList': 'Markers list',
      'ui.Done': 'Done',
      'ui.AddMarkerButton': 'Add',
      "ui.CancelMarkerButton": "Cancel",
      'ui.NewPathTitle': 'New Path',
      'ui.PathHelper': 'Hold Space to drag the map while drawing a path',
      'ui.AddRouteButton': 'Add',
      'ui.FinishPath': 'Finish',
      'ui.LockMarker': 'Lock markers',
      'ui.ImportExportHelper': 'Import and Export are only needed if you switch browser, or computer. For normal save use the header button.',
      'ui.ImportButton': 'Import save',
      'ui.ExportButton': 'Export save',
      'ui.SaveTitle': 'Save',
      'ui.DeleteMarkerButton': 'Delete all markers',
      'ui.DeletePathButton': 'Delete all paths',
      'ui.Help': 'How to use',
      'ui.HelpTitle': 'Help',
      'ui.DeleteButton': 'Delete',
      'toast.MarkerNameUpdated' : 'Marker name updated 💾',
      'toast.RouteNameSaved' : 'Route name saved 💾',
      'toast.PathFinished' : 'Path finished ✅',
      'toast.NoPath' : 'No current path',
      'toast.NoPathToDelete' : 'There is no path to delete',
      'toast.LoadingMap' : 'Loading Map...',
      'toast.SaveState' : '● Saved',
      'toast.UnsaveState' : '● Unsaved',
      'toast.SaveMarkerAndRoute' : 'Markers & routes saved locally 💾',
      'toast.FullMapDataImported' : 'Full map data imported ✅',
      'toast.PathImported' : 'Paths imported ✅',
      'toast.MarkerImported' : 'Markers imported ✅',
      'toast.WarnDeleteAllPath' : 'Do you really want to delete all paths from this map?',
      'toast.AllPathDeleted' : 'All paths cleared for this map 🧹',
      'toast.MarkerMapCleared' : 'Markers cleared for this map 🧹',
      'toast.CantLoadData' : 'Could not load user data:',
      'toast.CantSaveData' : 'Could not save user data locally:',
      'toast.PathInProgress' : 'Path in progress…',
      'toast.ExportAll' : 'All data have been saved 💾',
      'toast.SharedNoNewData': 'Nothing new to add from shared map ✅',
      'toast.ShareUrlCopied': 'Share link copied to clipboard 📋',
      'toast.SharedMerged': 'Shared markers and routes added to your map ✅',
      'toast.SharedTargetMissing': 'Original map not found. Maybe it was renamed or deleted ❌',
      'toast.MarkerDeleted': 'Marker deleted 🗑️',
      'toast.RouteDeleted': 'Route deleted 🧹',
      'ui.ShowHideGeneral': 'Show personal markers',
      'ui.ShowHideQuest': 'Show Quest',
      'ui.ShowHideBoss': 'Show Boss',
      'ui.ShowHideLoot': 'Show Loot',
      'ui.ShowHideWaypoint': 'Show Passage',
      'ui.ShowHideDonjon': 'Show Donjon',
      'ui.ShowHideNPC': 'Show NPC',
      'ui.DoneMarkersTitle': 'Completed markers',
      "ui.NothingDone": "Nothing done",
      'ui.ShowHideRegion' : 'Show/Hide Region names',
      'ui.ShowHideRift' : 'Show/Hide Rift',
      'ui.CenterOnMap': 'Center on map',
      'ui.ShareMapButton': 'Share my map',
      'ui.SharedViewLabel': 'Shared map (read-only)',
      'ui.SharedTargetLabel': 'Add to map:',
      'ui.SharedMergeButton': 'Add to my map',
      'ui.MergeRoutesButton': 'Add shared to my map',
      'ui.PathNamePlaceholder': 'Path name (optional)',
      'ui.MarkerNamePlaceholder': 'Name / note',
      'toast.WarnDeleteAllMarkers': 'Do you really want to delete all markers from this map?',
      'toast.NothingToShare': 'There is nothing to share (no routes or shared markers)',
      'ui.SearchLocationPlaceholder': 'Search locations or type / to search markers...',
      "ui.region":  "Region",
      "ui.rift":    "Rift",
      "ui.dungeon": "Dungeon",
      "ui.annouce": "Build your own experience",
      "character.NewCharacter" : "Create new character",
      "character.Edit" : "Edit",
      "confirmDeleteCharacter": "Delete character \"{name}\"?",
      "KeepOneCharacter": "You must keep at least one character.",

      "character.CreateButton" : "Create",
      "ui.NewCharacter": "New character",
      "ui.RenameCharacter": "Rename your character",
      "ui.CharacterNamePlaceHolder" : "Character name", 

      "ui.MaxLimitCharacter": "You cannot have more than 10 characters.",
      "ui.ShowAllMarker": "Show all",
      "toast.MarkerFiltered": "Marker added to \"{cat}\" (currently filtered)",
      "ui.DeleteNoteButton": "Delete all notes",
      "ui.DeleteNoteConfirm": "Delete all region notes? This cannot be undone.",
      "ui.NoteList": "Notes list",
      "toast.NoteDeleted": "Note deleted 🗑️",
      "toast.NoteSaved": "Note saved 💾",
      "KeyboardPan": "WASD to move map",
      "ui.ToggleSidebar": "Toggle sidebar",
      "toast.ShareCooldown" : "Please wait {wait}s before sharing again",
      "share.tooltip": "Share your full map.",
      "character.DuplicateToggle": "Duplicate an existing character",
      "character.DuplicateSourceLabel": "Character to duplicate →",

      "ui.HelpLine1": "You can select a map from the dropdown under the minimap (main or DLC)",
      "ui.Markers": "Markers",
      "ui.HelpLineMarker1": "Select New Marker, choose a category, name it, then click on the map to place it",
      "ui.Notes": "Notes",
      "ui.HelpLineNote": "You can add region notes by hovering over region names",
      "ui.Routes": "Routes",
      "ui.HelpLineRoute1": "Select New Route and click on the map to place the first point, then continue drawing",
      "ui.HelpLineRoute2": "Hold Space to move the map while drawing a route. Press Escape or the Finish button to complete it",
      "ui.HelpLineRoute3": "All routes are shared when you generate a shared link",
      "ui.Share": "Share",
      "ui.HelpLineShare1": "Click “Share my map” to generate a link containing your paths, notes, and shared markers",
      "ui.HelpLineShare2": "All paths and notes are shared, but only markers checked as “Shared” are included",
      "ui.HelpLineShare3": "Share your journey and quest notes, and contribute to a richer community map.",
      "ui.HelpLineTools": "Deleting all markers, routes, or notes in the Tools section only affects the active character",
      "character.AvatarLabel": "Choose an Avatar",
      "search.CustomLocalOnly": "Only custom markers and notes from the current map",
      "ui.shrine" : "Shrine",
      "ui.shrineTierNormal": "Normal mode",
      "ui.shrineTierElite": "Elite mode",
      "ui.shrineTierUltimate": "Ultimate mode",
      "ui.DonePanel": "Done panel",
      "ui.shrineTotal" : "Shrines completed",
      "ui.DeleteShrineButton": "Reset all shrines",
      "ui.ConfirmResetShrines": "Reset all shrines for this character?",
      "toast.ShrinesReset": "Shrines have been reset for this character.",
      "ui.readOnlyMessage": "Read-only view. To return to normal mode",
      "ui.readOnlyMessageLink": "click here",
      "ui.linkMarker": "Share marker",
      "ui.linkRoute": "Share route"

    },
    fr: {
      'ui.NewMarkerTitle': 'Nouveau marqueur',
      'ui.GeneralMarker': 'Repère perso',
      'ui.QuestMarker': 'Quête',
      'ui.BossMarker': 'Boss',
      'ui.LootMarker': 'Butin',
      'ui.WaypointMarker': 'Passage',
      'ui.DonjonMarker': 'Donjon',
      'ui.NPCMarker': 'PNJ',
      'ui.ToolsTitle': 'Outils',
      'ui.RoutesList': 'Liste des routes',
      'ui.MarkerList': 'Liste des marqueurs',
      'ui.Done': 'Terminé',
      'ui.AddMarkerButton': 'Ajouter',
      "ui.CancelMarkerButton": "Annuler",
      'ui.NewPathTitle': 'Nouveau tracé',
      'ui.PathHelper': 'Maintenir Espace pour déplacer la carte pendant un tracé',
      'ui.AddRouteButton': 'Ajouter',
      'ui.FinishPath': 'Terminer',
      'ui.LockMarker': 'Verrouiller les marqueurs',
      'ui.ImportExportHelper': 'Import/export uniquement si vous changez de navigateur ou d’ordinateur. Pour une sauvegarde normale, utilisez le bouton dans l’en-tête.',
      'ui.ImportButton': 'Importer une sauvegarde',
      'ui.ExportButton': 'Exporter la sauvegarde',
      'ui.SaveTitle': 'Sauvegarder',
      'ui.DeleteMarkerButton': 'Supprimer tous les marqueurs',
      'ui.DeletePathButton': 'Supprimer tous les tracés',
      'ui.Help': 'Guide d’utilisation',
      'ui.HelpTitle': 'Aide',
      'ui.DeleteButton': 'Supprimer',
      'toast.MarkerNameUpdated' : 'Nom du marqueur mis à jour 💾',
      'toast.RouteNameSaved' : 'Nom de la route sauvegardé 💾',
      'toast.PathFinished' : 'Tracé terminé ✅',
      'toast.NoPath' : 'Aucun tracé en cours',
      'toast.NoPathToDelete' : 'Il n’y a aucun tracé à supprimer',
      'toast.LoadingMap' : 'Chargement de la carte...',
      'toast.SaveState' : '● Sauvegardé',
      'toast.UnsaveState' : '● Non sauvegardé',
      'toast.SaveMarkerAndRoute' : 'Marqueurs et routes sauvegardés localement 💾',
      'toast.FullMapDataImported' : 'Données complètes importées ✅',
      'toast.PathImported' : 'Tracés importés ✅',
      'toast.MarkerImported' : 'Marqueurs importés ✅',
      'toast.WarnDeleteAllPath' : 'Voulez-vous vraiment supprimer tous les tracés de cette carte ?',
      'toast.AllPathDeleted' : 'Tous les tracés ont été supprimés 🧹',
      'toast.MarkerMapCleared' : 'Marqueurs supprimés pour cette carte 🧹',
      'toast.CantLoadData' : 'Impossible de charger les données utilisateur :',
      'toast.CantSaveData' : 'Impossible d’enregistrer les données localement :',
      'toast.PathInProgress' : 'Tracé en cours…',
      'toast.ExportAll' : 'Toutes les données ont été sauvegardées 💾',
      'toast.SharedNoNewData': 'Aucune nouvelle donnée à ajouter depuis la carte partagée ✅',
      'toast.MarkerDeleted': 'Marqueur supprimé 🗑️',
      'toast.RouteDeleted': 'Tracé supprimé 🧹',
      'ui.DoneMarkersTitle': "Marqueurs terminés",
      "ui.NothingDone": "Rien de terminé", 
      'ui.ShowHideGeneral': 'Afficher repères perso',
      'ui.ShowHideQuest': 'Afficher Quêtes',
      'ui.ShowHideBoss': 'Afficher Boss',
      'ui.ShowHideLoot': 'Afficher Butin',
      'ui.ShowHideWaypoint': 'Afficher Passage',
      'ui.ShowHideDonjon': 'Afficher Donjons',
      'ui.ShowHideNPC': 'Afficher PNJ',
      'ui.CenterOnMap': 'Centrer sur la carte',
      'ui.ShowHideRegion': 'Afficher/Masquer les noms de régions',
      'ui.ShowHideRift': 'Afficher/Masquer les failles (Rifts)',
      'toast.ShareUrlCopied': 'Lien de partage copié dans le presse-papiers 📋',
      'toast.SharedMerged': 'Marqueurs et tracés partagés ajoutés à votre carte ✅',
      'toast.SharedTargetMissing': 'Carte d’origine introuvable. Elle a peut-être été renommée ou supprimée ❌',
      'ui.ShareMapButton': 'Partager ma carte',
      'ui.SharedViewLabel': 'Carte partagée (lecture seule)',
      'ui.SharedTargetLabel': 'Ajouter à la carte :',
      'ui.SharedMergeButton': 'Ajouter à ma carte',
     'ui.MergeRoutesButton': 'Ajouter le partage à ma carte',
      'ui.PathNamePlaceholder': 'Nom du trajet (optionnel)',
      'ui.MarkerNamePlaceholder': 'Nom / note',
      'toast.WarnDeleteAllMarkers': 'Voulez-vous vraiment supprimer tous les marqueurs de cette carte ?',
      'toast.NothingToShare': 'Aucune route et aucun marqueur partagé. Cochez « Partagé » pour les inclure dans le lien !',
      'ui.SearchLocationPlaceholder': 'Rechercher un lieu ou taper / pour chercher des marqueurs...',
      "ui.region":  "Région",
      "ui.rift":    "Faille",
      "ui.dungeon": "Donjon",
      "ui.annouce": "Créez votre propre expérience",
      "character.NewCharacter": "Créer un nouveau personnage",
      "character.Edit": "Renommer",
      "character.CreateButton": "Créer",
      "ui.NewCharacter": "Nouveau personnage",
      "ui.RenameCharacter": "Renommer votre personnage",
      "ui.CharacterNamePlaceHolder": "Nom du personnage",      
      "confirmDeleteCharacter": "Supprimer le personnage « {name} » ?",
      "KeepOneCharacter": "Vous devez garder au moins un personnage.",
      "ui.MaxLimitCharacter": "Vous ne pouvez pas avoir plus de 10 personnages.",
      "ui.ShowAllMarker": "Tout afficher",
      "toast.MarkerFiltered": "Marqueur ajouté dans « {cat} » (actuellement filtré)",
      "ui.DeleteNoteButton": "Supprimer toutes les notes",
      "ui.DeleteNoteConfirm": "Supprimer toutes les notes de région ? Cette action est définitive.",
      "ui.NoteList": "Liste des notes",
      "toast.NoteDeleted": "Note supprimée 🗑️",
      "toast.NoteSaved": "Note enregistrée 💾",     
      "KeyboardPan": "QZSD pour déplacer la carte",
      "ui.ToggleSidebar": "Replier la barre latérale",
      "toast.ShareCooldown": "Veuillez attendre {wait}s avant de partager à nouveau.",
      "share.tooltip": "Pour partager votre carte complète.",
      "character.DuplicateToggle": "Dupliquer un personnage existant",
      "character.DuplicateSourceLabel": "Personnage à dupliquer →",

      "ui.HelpLine1": "Vous pouvez sélectionner une carte dans la liste sous la mini-carte (principale ou DLC)",
      "ui.Markers": "Marqueurs",
      "ui.HelpLineMarker1": "Sélectionnez « Nouveau marqueur », choisissez une catégorie, nommez-le puis cliquez sur la carte",
      "ui.Notes": "Notes",
      "ui.HelpLineNote": "Vous pouvez ajouter des notes de région en survolant le nom des régions",
      "ui.Routes": "Tracés",
      "ui.HelpLineRoute1": "Sélectionnez « Nouveau tracé » puis cliquez sur la carte pour placer le premier point",
      "ui.HelpLineRoute2": "Maintenez Espace pour déplacer la carte pendant un tracé. Appuyez sur Échap ou sur Terminer pour le finaliser",
      "ui.HelpLineRoute3": "Tous les tracés sont partagés lorsque vous générez un lien",
      "ui.Share": "Partage",
      "ui.HelpLineShare1": "Cliquez sur « Partager ma carte » pour générer un lien contenant vos tracés vos notes, et vos marqueurs partagés",
      "ui.HelpLineShare2": "Tous les tracés et notes sont partagés, mais seuls les marqueurs cochés « Partagé » sont inclus",
      "ui.HelpLineShare3": "Partagez ainsi votre aventure et vos notes de quêtes, et contribuez à une carte communautaire enrichie.",
      "ui.HelpLineTools": "Supprimer tous les marqueurs, tracés ou notes dans la section Outils n'affecte que le personnage actif",
      "character.AvatarLabel": "Choisir un Avatar",
      "search.CustomLocalOnly": "Uniquement les marqueurs et notes personnalisés de la carte actuelle",
      "ui.shrine": "Sanctuaire",
      "ui.shrineTierNormal": "Mode Normal",
      "ui.shrineTierElite": "Mode Élite",
      "ui.shrineTierUltimate": "Mode Ultime",
      "ui.DonePanel": "Panneau des complétés",
      "ui.shrineTotal": "Sanctuaires complétés",
      "ui.DeleteShrineButton": "Réinitialiser tous les sanctuaires",
      "ui.ConfirmResetShrines": "Réinitialiser tous les sanctuaires pour ce personnage ?",
      "toast.ShrinesReset": "Les sanctuaires ont été réinitialisés pour ce personnage.",
      "ui.readOnlyMessage": "Vue en lecture seul seulement. Pour la vue normal",
      "ui.readOnlyMessageLink": "cliquez ici",
      "ui.linkMarker" : "Partager un marqueur",
      "ui.linkRoute" : "Partager la route",

    },
    es: {
      'ui.NewMarkerTitle': 'Nuevo marcador',
      'ui.GeneralMarker': 'Marcador personal',
      'ui.QuestMarker': 'Misión',
      'ui.BossMarker': 'Jefe',
      'ui.LootMarker': 'Botín',
      'ui.WaypointMarker': 'Pasaje',
      'ui.DonjonMarker': 'Mazmorra',
      'ui.NPCMarker': 'NPC',
      'ui.ToolsTitle': 'Herramientas',
      'ui.RoutesList': 'Lista de rutas',
      'ui.MarkerList': 'Lista de marcadores',
      'ui.Done': 'Hecho',
      'ui.AddMarkerButton': 'Añadir',
      "ui.CancelMarkerButton": "Cancelar",
      'ui.NewPathTitle': 'Nuevo recorrido',
      'ui.PathHelper': 'Mantén Espacio para mover el mapa mientras dibujas el recorrido',
      'ui.AddRouteButton': 'Añadir',
      'ui.FinishPath': 'Terminar',
      'ui.LockMarker': 'Bloquear marcadores',
      'ui.ImportExportHelper': "Importar/exportar solo si cambias de navegador o de ordenador. Para guardar normalmente, usa el botón en el encabezado.",
      'ui.ImportButton': 'Importar guardado',
      'ui.ExportButton': 'Exportar guardado',
      'ui.SaveTitle': 'Guardar',
      'ui.DeleteMarkerButton': 'Eliminar todos los marcadores',
      'ui.DeletePathButton': 'Eliminar todos los recorridos',
      'ui.Help': 'Cómo usar',
      'ui.HelpTitle': 'Ayuda',
      'ui.DeleteButton': 'Eliminar',
      'ui.CenterOnMap': 'Centrar en el mapa',
      'ui.ShowHideGeneral': 'Mostrar marcadores personales',
      'ui.ShowHideQuest': 'Mostrar Misiones',
      'ui.ShowHideBoss': 'Mostrar Jefes',
      'ui.ShowHideLoot': 'Mostrar Botín',
      'ui.ShowHideWaypoint': 'Mostrar Pasaje',
      'ui.ShowHideDonjon': 'Mostrar Mazmorras',
      'ui.ShowHideNPC': 'Mostrar NPC',
      'ui.ShowHideRegion': 'Mostrar/Ocultar nombres de regiones',
      'ui.ShowHideRift': 'Mostrar/Ocultar grietas',
      'ui.DoneMarkersTitle': "Marcadores completados",
      "ui.NothingDone": "Nada completado",
      'toast.MarkerNameUpdated': 'Nombre del marcador actualizado 💾',
      'toast.RouteNameSaved': 'Nombre de la ruta guardado 💾',
      'toast.PathFinished': 'Recorrido terminado ✅',
      'toast.NoPathToDelete' : 'No hay rutas que eliminar',
      'toast.NoPath': 'No hay recorrido en curso',
      'toast.LoadingMap': 'Cargando mapa...',
      'toast.SaveState': '● Guardado',
      'toast.UnsaveState': '● No guardado',
      'toast.SaveMarkerAndRoute': 'Marcadores y rutas guardados localmente 💾',
      'toast.FullMapDataImported': 'Datos completos importados ✅',
      'toast.PathImported': 'Recorridos importados ✅',
      'toast.MarkerImported': 'Marcadores importados ✅',
      'toast.WarnDeleteAllPath': '¿Realmente deseas eliminar todos los recorridos de este mapa?',
      'toast.AllPathDeleted': 'Todos los recorridos eliminados 🧹',
      'toast.MarkerMapCleared': 'Marcadores eliminados para este mapa 🧹',
      'toast.CantLoadData': 'No se pudieron cargar los datos del usuario:',
      'toast.CantSaveData': 'No se pudieron guardar los datos localmente:',
      'toast.PathInProgress': 'Recorrido en progreso…',
      'toast.ExportAll': 'Todos los datos se han guardado 💾',
      'toast.MarkerDeleted': 'Marcador eliminado 🗑️',
      'toast.RouteDeleted': 'Ruta eliminada 🧹',
      'toast.ShareUrlCopied': 'Enlace de compartición copiado al portapapeles 📋',
      'toast.SharedMerged': 'Marcadores y rutas compartidos añadidos a tu mapa ✅',
      'toast.SharedTargetMissing': 'Mapa original no encontrado. Puede que se haya renombrado o eliminado ❌',
      'ui.ShareMapButton': 'Compartir mi mapa',
      'ui.SharedViewLabel': 'Mapa compartido (solo lectura)',
      'ui.SharedTargetLabel': 'Agregar al mapa:',
      'ui.SharedMergeButton': 'Agregar a mi mapa',
      'ui.MergeRoutesButton': 'Agregar el compartido a mi mapa',
      'ui.PathNamePlaceholder': 'Nombre del recorrido (opcional)',
      'ui.MarkerNamePlaceholder': 'Nombre / nota',
      'toast.WarnDeleteAllMarkers': '¿Realmente deseas eliminar todos los marcadores de este mapa?',
      'toast.NothingToShare': 'No hay rutas ni marcadores compartidos. Marca “Compartido” para incluirlos en tu enlace.',
      'ui.SearchLocationPlaceholder': 'Buscar ubicación o escribir / para buscar marcadores...',
      "ui.region":  "Región",
      "ui.rift":    "Grieta",
      "ui.dungeon": "Mazmorra",
      "ui.annouce": "Crea tu propia experiencia",
      "character.NewCharacter": "Crear nuevo personaje",
      "character.Edit": "Editar",
      "confirmDeleteCharacter": "¿Eliminar el personaje \"{name}\"?",
      "KeepOneCharacter": "Debes mantener al menos un personaje.",
      "character.CreateButton": "Crear",
      "ui.NewCharacter": "Nuevo personaje",
      "ui.RenameCharacter": "Renombrar tu personaje",
      "ui.CharacterNamePlaceHolder": "Nombre del personaje",
      "ui.MaxLimitCharacter": "No puedes tener más de 10 personajes.",
      "ui.ShowAllMarker": "Mostrar todo",
      "toast.MarkerFiltered": "Marcador añadido a \"{cat}\" (actualmente filtrado)",
      "ui.DeleteNoteButton": "Eliminar todas las notas",
      "ui.DeleteNoteConfirm": "¿Eliminar todas las notas de región? Esta acción no se puede deshacer.",
      "ui.NoteList": "Lista de notas",
      "toast.NoteDeleted": "Nota eliminada 🗑️",
      "toast.NoteSaved": "Nota guardada 💾",
      "KeyboardPan": "WASD para mover el mapa",
      "ui.ToggleSidebar": "Alternar barra lateral",
      "toast.ShareCooldown": "Por favor espera {wait}s antes de compartir de nuevo.",
      "share.tooltip": "Comparte tu mapa completo.",
      "character.DuplicateToggle": "Duplicar un personaje existente",
      "character.DuplicateSourceLabel": "Personaje a duplicar →",

      "ui.HelpLine1": "Puedes seleccionar un mapa desde el menú bajo el minimapa (principal o DLC)",
      "ui.Markers": "Marcadores",
      "ui.HelpLineMarker1": "Selecciona Nuevo marcador, elige una categoría, ponle un nombre y haz clic en el mapa",
      "ui.Notes": "Notas",
      "ui.HelpLineNote": "Puedes añadir notas de región pasando el cursor sobre los nombres de las regiones",
      "ui.Routes": "Rutas",
      "ui.HelpLineRoute1": "Selecciona Nueva ruta y haz clic en el mapa para el primer punto, luego continúa dibujando",
      "ui.HelpLineRoute2": "Mantén Espacio para mover el mapa mientras dibujas. Pulsa Escape o el botón Finalizar para completar la ruta",
      "ui.HelpLineRoute3": "Todas las rutas se comparten al generar un enlace",
      "ui.Share": "Compartir",
      "ui.HelpLineShare1": "Haz clic en «Compartir mi mapa» para generar un enlace que contenga tus rutas, notas y marcadores compartidos",
      "ui.HelpLineShare2": "Todas las rutas y notas se comparten, pero solo se incluyen los marcadores marcados como «Compartido»",
      "ui.HelpLineShare3": "Comparte tu aventura y tus notas de misiones, y contribuye a un mapa comunitario más completo.",
      "ui.HelpLineTools": "Eliminar marcadores, rutas o notas desde la sección de herramientas solo afecta al personaje activo",
      "character.AvatarLabel": "Elegir un avatar",
      "search.CustomLocalOnly": "Solo marcadores y notas personalizadas del mapa actual",
      "ui.shrine": "Santuario",
      "ui.shrineTierNormal": "Modo Normal",
      "ui.shrineTierElite": "Modo Élite",
      "ui.shrineTierUltimate": "Modo Definitivo",
      "ui.DonePanel": "Panel de completados",
      "ui.shrineTotal": "Santuarios completados",      
      "ui.DeleteShrineButton": "Restablecer todos los santuarios",
      "ui.ConfirmResetShrines": "¿Restablecer todos los santuarios para este personaje?",
      "toast.ShrinesReset": "Los santuarios han sido restablecidos para este personaje.",
      "ui.readOnlyMessage": "Vista de solo lectura. Para volver al modo normal",
      "ui.readOnlyMessageLink": "haz clic aquí",
      "ui.linkMarker": "Compartir marcador",
      "ui.linkRoute": "Compartir ruta",

    },

    de: {
      "ui.NewMarkerTitle": "Neuer Marker",
      "ui.GeneralMarker": "Persönlicher Punkt",
      "ui.QuestMarker": "Quest",
      "ui.BossMarker": "Boss",
      "ui.LootMarker": "Beute",
      "ui.WaypointMarker": "Durchgang",
      "ui.DonjonMarker": "Dungeon",
      "ui.NPCMarker": "NPC",
      "ui.ToolsTitle": "Werkzeuge",
      "ui.RoutesList": "Routenliste",
      "ui.MarkerList": "Markerliste",
      "ui.Done": "Fertig",
      "ui.AddMarkerButton": "Hinzufügen",
      "ui.CancelMarkerButton": "Abbrechen",
      "ui.NewPathTitle": "Neuer Pfad",
      "ui.PathHelper": "Halte die Leertaste gedrückt, um die Karte während des Zeichnens zu bewegen",
      "ui.AddRouteButton": "Hinzufügen",
      "ui.FinishPath": "Beenden",
      "ui.LockMarker": "Marker sperren",
      "ui.ImportExportHelper": "Import und Export werden nur benötigt, wenn du den Browser oder den Computer wechselst. Für normales Speichern benutze die Schaltfläche oben.",
      "ui.ImportButton": "Speichern importieren",
      "ui.ExportButton": "Speichern exportieren",
      "ui.SaveTitle": "Speichern",
      "ui.DeleteMarkerButton": "Alle Marker löschen",
      "ui.DeletePathButton": "Alle Pfade löschen",
      "ui.Help": "Anleitung",
      "ui.HelpTitle": "Hilfe",
      "ui.DeleteButton": "Löschen",
      "toast.MarkerNameUpdated": "Markername aktualisiert 💾",
      "toast.RouteNameSaved": "Routenname gespeichert 💾",
      "toast.PathFinished": "Pfad abgeschlossen ✅",
      "toast.NoPath": "Kein aktueller Pfad",
      "toast.NoPathToDelete": "Es gibt keinen Pfad zum Löschen",
      "toast.LoadingMap": "Karte wird geladen...",
      "toast.SaveState": "● Gespeichert",
      "toast.UnsaveState": "● Nicht gespeichert",
      "toast.SaveMarkerAndRoute": "Marker und Routen lokal gespeichert 💾",
      "toast.FullMapDataImported": "Komplette Kartendaten importiert ✅",
      "toast.PathImported": "Pfade importiert ✅",
      "toast.MarkerImported": "Marker importiert ✅",
      "toast.WarnDeleteAllPath": "Möchtest du wirklich alle Pfade von dieser Karte löschen?",
      "toast.AllPathDeleted": "Alle Pfade gelöscht 🧹",
      "toast.MarkerMapCleared": "Marker von dieser Karte gelöscht 🧹",
      "toast.CantLoadData": "Benutzerdaten konnten nicht geladen werden:",
      "toast.CantSaveData": "Benutzerdaten konnten nicht lokal gespeichert werden:",
      "toast.PathInProgress": "Pfad in Bearbeitung…",
      "toast.ExportAll": "Alle Daten wurden gespeichert 💾",
      "toast.SharedNoNewData": "Keine neuen Daten zum Hinzufügen ✅",
      "toast.ShareUrlCopied": "Freigabelink in die Zwischenablage kopiert 📋",
      "toast.SharedMerged": "Geteilte Marker und Routen hinzugefügt ✅",
      "toast.SharedTargetMissing": "Originalkarte nicht gefunden. Vielleicht wurde sie umbenannt oder gelöscht ❌",
      "toast.MarkerDeleted": "Marker gelöscht 🗑️",
      "toast.RouteDeleted": "Route gelöscht 🧹",
      "ui.ShowHideGeneral": "Persönliche Marker anzeigen",
      "ui.ShowHideQuest": "Quests anzeigen",
      "ui.ShowHideBoss": "Bosse anzeigen",
      "ui.ShowHideLoot": "Beute anzeigen",
      "ui.ShowHideWaypoint": "Durchgänge anzeigen",
      "ui.ShowHideDonjon": "Dungeon anzeigen",
      "ui.ShowHideNPC": "NPCs anzeigen",
      'ui.DoneMarkersTitle': "Abgeschlossene Markierungen",
      "ui.NothingDone": "Nichts abgeschlossen",
      'ui.ShowHideRegion': 'Regionnamen ein-/ausblenden',
      'ui.ShowHideRift': 'Risse ein-/ausblenden',
      "ui.CenterOnMap": "Auf Karte zentrieren",
      "ui.ShareMapButton": "Meine Karte teilen",
      "ui.SharedViewLabel": "Geteilte Karte (nur Ansicht)",
      "ui.SharedTargetLabel": "Hinzufügen zu Karte:",
      "ui.SharedMergeButton": "Zu meiner Karte hinzufügen",
      "ui.MergeRoutesButton": "Geteilte zu meiner Karte hinzufügen",
      "ui.PathNamePlaceholder": "Pfadname (optional)",
      "ui.MarkerNamePlaceholder": "Name / Notiz",
      "toast.WarnDeleteAllMarkers": "Möchtest du wirklich alle Marker von dieser Karte löschen?",
      "toast.NothingToShare": "Nichts zum Teilen vorhanden (keine Routen oder geteilte Marker)",
      'ui.SearchLocationPlaceholder': 'Ort suchen oder / eingeben, um Marker zu durchsuchen...',
      "ui.region":  "Region",
      "ui.rift":    "Riss",
      "ui.dungeon": "Dungeon",
      "ui.annouce": "Gestalte dein eigenes Erlebnis",
      "character.NewCharacter": "Neuen Charakter erstellen",
      "character.Edit": "Bearbeiten",
      "confirmDeleteCharacter": "Charakter „{name}“ löschen?",
      "character.CreateButton": "Erstellen",
      "ui.NewCharacter": "Neuer Charakter",
      "ui.RenameCharacter": "Charakter umbenennen",
      "ui.CharacterNamePlaceHolder": "Charaktername",
      "KeepOneCharacter": "Du musst mindestens einen Charakter behalten.",
      "ui.MaxLimitCharacter": "Du kannst nicht mehr als 10 Charaktere haben.",
      "ui.ShowAllMarker": "Alles anzeigen",
      "toast.MarkerFiltered": "Marker zu \"{cat}\" hinzugefügt (derzeit gefiltert)",
      "ui.DeleteNoteButton": "Alle Notizen löschen",
      "ui.DeleteNoteConfirm": "Alle Regionsnotizen löschen? Dies kann nicht rückgängig gemacht werden.",
      "ui.NoteList": "Notizliste",
      "toast.NoteDeleted": "Notiz gelöscht 🗑️",
      "toast.NoteSaved": "Notiz gespeichert 💾",
      "KeyboardPan": "WASD zum Bewegen der Karte",
      "ui.ToggleSidebar": "Seitenleiste umschalten",
      "toast.ShareCooldown": "Bitte warten Sie {wait}s, bevor Sie erneut teilen.",
      "share.tooltip": "Teile deine komplette Karte.",
      "character.DuplicateToggle": "Vorhandenen Charakter duplizieren",
      "character.DuplicateSourceLabel": "Zu duplizierender Charakter →",

      "ui.HelpLine1": "Sie können eine Karte im Menü unter der Minikarte auswählen (Hauptkarte oder DLC)",
      "ui.Markers": "Marker",
      "ui.HelpLineMarker1": "Wählen Sie Neuer Marker, Kategorie auswählen, benennen und auf die Karte klicken",
      "ui.Notes": "Notizen",
      "ui.HelpLineNote": "Sie können Regionsnotizen hinzufügen, indem Sie über die Regionsnamen fahren",
      "ui.Routes": "Routen",
      "ui.HelpLineRoute1": "Wählen Sie Neue Route und klicken Sie für den ersten Punkt auf die Karte",
      "ui.HelpLineRoute2": "Halten Sie die Leertaste, um die Karte während des Zeichnens zu bewegen. Escape oder Fertig stellen beendet die Route",
      "ui.HelpLineRoute3": "Alle Routen werden geteilt, wenn Sie einen Freigabelink erstellen",
      "ui.Share": "Teilen",
      "ui.HelpLineShare1": "Klicke auf „Meine Karte teilen“, um einen Link zu erzeugen, der deine Pfade, Notizen und geteilten Markierungen enthält",
      "ui.HelpLineShare2": "Alle Pfade und Notizen werden geteilt, aber nur Markierungen, die als „Geteilt“ markiert sind, werden einbezogen",
     "ui.HelpLineShare3": "Teile dein Abenteuer und deine Quest-Notizen und trage zu einer erweiterten Community-Karte bei.",
      "ui.HelpLineTools": "Das Löschen aller Marker, Routen oder Notizen betrifft nur den aktiven Charakter",
      "character.AvatarLabel": "Avatar auswählen",
      "search.CustomLocalOnly": "Nur eigene Markierungen und Notizen der aktuellen Karte",
      "ui.shrineTierNormal": "Normalmodus",
      "ui.shrineTierElite": "Elitemodus",
      "ui.shrineTierUltimate": "Ultimativer Modus",
      "ui.DonePanel": "Abgeschlossen-Panel",
      "ui.shrineTotal": "Abgeschlossene Schreine",
      "ui.DeleteShrineButton": "Alle Schreine zurücksetzen",
      "ui.ConfirmResetShrines": "Alle Schreine für diesen Charakter zurücksetzen?",
      "toast.ShrinesReset": "Die Schreine wurden für diesen Charakter zurückgesetzt.",
      "ui.shrine": "Schrein",
      "ui.readOnlyMessage": "Nur-Lese-Ansicht. Um zum normalen Modus zurückzukehren",
      "ui.readOnlyMessageLink": "klicken Sie hier",
      "ui.linkMarker": "Marker teilen",
      "ui.linkRoute": "Route teilen",

    },

  pt: {
    'ui.NewMarkerTitle': 'Novo marcador',
    'ui.GeneralMarker': 'Marcador pessoal',
    'ui.QuestMarker': 'Missão',
    'ui.BossMarker': 'Chefe',
    'ui.LootMarker': 'Tesouro',
    'ui.WaypointMarker': 'Passagem',
    'ui.DonjonMarker': 'Masmorra',
    'ui.NPCMarker': 'NPC',
    'ui.ToolsTitle': 'Ferramentas',
    'ui.RoutesList': 'Lista de rotas',
    'ui.MarkerList': 'Lista de marcadores',
    'ui.Done': 'Concluído',
    'ui.AddMarkerButton': 'Adicionar',
    "ui.CancelMarkerButton": "Cancelar",
    'ui.NewPathTitle': 'Novo trajeto',
    'ui.PathHelper': 'Segure a barra de espaço para mover o mapa enquanto desenha o trajeto',
    'ui.AddRouteButton': 'Adicionar',
    'ui.FinishPath': 'Finalizar',
    'ui.LockMarker': 'Bloquear marcadores',
    'ui.ImportExportHelper': "Use importar/exportar apenas se mudar de navegador ou computador. Para salvar normalmente, use o botão no cabeçalho.",
    'ui.ImportButton': 'Importar salvamento',
    'ui.ExportButton': 'Exportar salvamento',
    'ui.SaveTitle': 'Salvar',   
    'ui.DeleteMarkerButton': 'Excluir todos os marcadores',
    'ui.DeletePathButton': 'Excluir todos os trajetos',
    'ui.Help': 'Como usar',
    'ui.HelpTitle': 'Ajuda',
    'ui.DeleteButton': 'Excluir',
    'ui.CenterOnMap': 'Centralizar no mapa',
     'toast.ExportAll': 'Todos os dados foram salvos 💾',
     'toast.ShareUrlCopied': 'Link de compartilhamento copiado para a área de transferência 📋',
    'ui.ShowHideGeneral': 'Mostrar marcadores pessoais',
    'ui.ShowHideQuest': 'Mostrar Missões',
    'ui.ShowHideBoss': 'Mostrar Chefes',
    'ui.ShowHideLoot': 'Mostrar Tesouros',
    'ui.ShowHideWaypoint': 'Mostrar Passagem',
    'ui.ShowHideDonjon': 'Mostrar Masmorras',
    'ui.ShowHideNPC': 'Mostrar NPC',
    'ui.ShowHideRegion': 'Mostrar nomes das regiões',
    'ui.ShowHideRift': 'Mostrar fendas',
    'ui.DoneMarkersTitle': "Marcadores concluídos",
    "ui.NothingDone": "Nada concluído",  
    'toast.MarkerNameUpdated': 'Nome do marcador atualizado 💾',
    'toast.RouteNameSaved': 'Nome da rota salvo 💾',
    'toast.PathFinished': 'Trajeto finalizado ✅',
    'toast.NoPath': 'Nenhum trajeto em andamento',
    'toast.NoPathToDelete' : 'Não há trajetos para excluir',
    'toast.LoadingMap': 'Carregando mapa...',
    'toast.SaveState': '● Salvo',
    'toast.UnsaveState': '● Não salvo',
    'toast.SaveMarkerAndRoute': 'Marcadores e rotas foram salvos localmente 💾',
    'toast.FullMapDataImported': 'Todos os dados importados ✅',
    'toast.PathImported': 'Trajetos importados ✅',
    'toast.MarkerImported': 'Marcadores importados ✅',
    'toast.WarnDeleteAllPath': 'Tem certeza de que deseja excluir todos os trajetos deste mapa?',
    'toast.AllPathDeleted': 'Todos os trajetos foram excluídos 🧹',
    'toast.MarkerMapCleared': 'Marcadores excluídos deste mapa 🧹',
    'toast.CantLoadData': 'Não foi possível carregar os dados do usuário:',
    'toast.CantSaveData': 'Não foi possível salvar os dados localmente:',
    'toast.PathInProgress': 'Trajeto em andamento…',
    'toast.ExportAll': 'Todos os dados foram salvos 💾',
    'toast.MarkerDeleted': 'Marcador excluído 🗑️',
    'toast.RouteDeleted': 'Rota excluída 🧹',
    'toast.ShareUrlCopied': 'Link de compartilhamento copiado para a área de transferência 📋',
    'toast.SharedMerged': 'Marcadores e rotas compartilhados adicionados ao seu mapa ✅',
    'toast.SharedTargetMissing': 'Mapa original não encontrado. Pode ter sido renomeado ou excluído ❌',
    'ui.ShareMapButton': 'Compartilhar meu mapa',
    'ui.SharedViewLabel': 'Mapa compartilhado (somente leitura)',
    'ui.SharedTargetLabel': 'Adicionar ao mapa:',
    'ui.SharedMergeButton': 'Adicionar ao meu mapa',
    'ui.MergeRoutesButton': 'Adicionar compartilhado ao meu mapa',
     'ui.PathNamePlaceholder': 'Nome do trajeto (opcional)',
     'ui.MarkerNamePlaceholder': 'Nome / anotação',
     'toast.WarnDeleteAllMarkers': 'Tem certeza de que deseja excluir todos os marcadores deste mapa?',
     'toast.NothingToShare': 'Nenhuma rota ou marcador compartilhado. Marque “Compartilhado” para incluí-los no link!',
     'ui.SearchLocationPlaceholder': 'Pesquisar local ou digitar / para buscar marcadores...',
     "ui.region":  "Região",
      "ui.rift":    "Fenda",
      "ui.dungeon": "Masmorra",
      "ui.annouce": "Crie sua própria experiência",
      "character.NewCharacter": "Criar novo personagem",
      "character.Edit": "Editar",
     "character.CreateButton": "Criar",
      "ui.NewCharacter": "Novo personagem",
      "ui.RenameCharacter": "Renomear seu personagem",
      "ui.CharacterNamePlaceHolder": "Nome do personagem",
      "confirmDeleteCharacter": "Excluir o personagem \"{name}\"?",
      "KeepOneCharacter": "Você deve manter pelo menos um personagem.",
      "ui.MaxLimitCharacter": "Você não pode ter mais de 10 personagens.",
      "ui.ShowAllMarker": "Mostrar tudo",
      "toast.MarkerFiltered": "Marcador adicionado a \"{cat}\" (atualmente filtrado)",
      "ui.DeleteNoteButton": "Apagar todas as notas",
      "ui.DeleteNoteConfirm": "Apagar todas as notas da região? Esta ação não pode ser revertida.",
      "ui.NoteList": "Lista de notas",
      "toast.NoteDeleted": "Nota apagada 🗑️",
       "toast.NoteSaved": "Nota salva 💾",
      "KeyboardPan": "WASD para mover o mapa",
      "ui.ToggleSidebar": "Alternar barra lateral",
      "toast.ShareCooldown": "Aguarde {wait}s antes de compartilhar novamente.",
      "share.tooltip": "Partilhar o mapa completo.",
      "character.DuplicateToggle": "Duplicar um personagem existente",
      "character.DuplicateSourceLabel": "Personagem a duplicar →",

      "ui.HelpLine1": "Você pode selecionar um mapa no menu abaixo do minimapa (principal ou DLC)",
      "ui.Markers": "Marcadores",
      "ui.HelpLineMarker1": "Selecione Novo marcador, escolha uma categoria, nomeie-o e clique no mapa",
      "ui.Notes": "Notas",
      "ui.HelpLineNote": "Você pode adicionar notas de região passando o cursor sobre os nomes das regiões",
      "ui.Routes": "Rotas",
      "ui.HelpLineRoute1": "Selecione Nova rota e clique no mapa para o primeiro ponto, depois continue desenhando",
      "ui.HelpLineRoute2": "Segure Espaço para mover o mapa durante o desenho. Pressione Escape ou Finalizar para concluir",
      "ui.HelpLineRoute3": "Todas as rotas são compartilhadas ao gerar um link",
      "ui.Share": "Compartilhar",
      "ui.HelpLineShare1": "Clique em “Compartilhar meu mapa” para gerar um link contendo seus caminhos, notas e marcadores compartilhados",
      "ui.HelpLineShare2": "Todos os caminhos e notas são compartilhados, mas apenas os marcadores marcados como “Compartilhado” são incluídos",
     "ui.HelpLineShare3": "Compartilhe sua jornada e suas anotações de missões, e contribua para um mapa comunitário mais completo.",
      "ui.HelpLineTools": "Excluir marcadores, rotas ou notas na seção Ferramentas afeta apenas o personagem ativo",
      "character.AvatarLabel": "Escolher um avatar",
      "search.CustomLocalOnly": "Apenas marcadores e notas personalizadas do mapa atual",
      "ui.shrineTierNormal": "Modo Normal",
      "ui.shrineTierElite": "Modo Elite",
      "ui.shrineTierUltimate": "Modo Supremo",
      "ui.DonePanel": "Painel de concluídos",
      "ui.shrineTotal": "Santuários concluídos",
      "ui.DeleteShrineButton": "Redefinir todos os santuários",
      "ui.ConfirmResetShrines": "Redefinir todos os santuários para este personagem?",
      "toast.ShrinesReset": "Os santuários foram redefinidos para este personagem.",
      "ui.shrine": "Santuário",
      "ui.readOnlyMessage": "Visualização somente leitura. Para voltar ao modo normal",
      "ui.readOnlyMessageLink": "clique aqui",
      "ui.linkMarker": "Compartilhar marcador",
      "ui.linkRoute": "Compartilhar rota",

  },

  ru: {
    'ui.NewMarkerTitle': 'Новый маркер',
    'ui.GeneralMarker': 'Личная отметка',
    'ui.QuestMarker': 'Задание',
    'ui.BossMarker': 'Босс',
    'ui.LootMarker': 'Добыча',
    'ui.WaypointMarker': 'Проход',
    'ui.DonjonMarker': 'Подземелье',
    'ui.NPCMarker': 'NPC',
    'ui.ToolsTitle': 'Инструменты',
    'ui.RoutesList': 'Список маршрутов',
    'ui.MarkerList': 'Список меток',
    'ui.Done': 'Готово',
    'ui.AddMarkerButton': 'Добавить',
    "ui.CancelMarkerButton": "Отмена",
    'ui.NewPathTitle': 'Новый путь',
    'ui.PathHelper': 'Удерживайте пробел, чтобы двигать карту во время рисования пути',
    'ui.AddRouteButton': 'Добавить',
    'ui.FinishPath': 'Завершить',
    'ui.LockMarker': 'Заблокировать маркеры',
    'ui.ImportExportHelper': "Используйте импорт/экспорт только при смене браузера или компьютера. Для обычного сохранения используйте кнопку в верхней панели.",
    'ui.ImportButton': 'Импортировать сохранение',
    'ui.ExportButton': 'Экспортировать сохранение',
    'ui.SaveTitle': 'Сохранить',    
    'ui.DeleteMarkerButton': 'Удалить все маркеры',
    'ui.DeletePathButton': 'Удалить все пути',
    'ui.Help': 'Как использовать',
    'ui.HelpTitle': 'Помощь',
    'ui.DeleteButton': 'Удалить',
    'ui.CenterOnMap': 'Центрировать на карте',
    'ui.ShowHideGeneral': 'Показать личные отметки',
    'ui.ShowHideQuest': 'Показать Квесты',
    'ui.ShowHideBoss': 'Показать боссов',
    'ui.ShowHideLoot': 'Показать Добычу',
    "ui.ShowHideWaypoint": "Показать проходы",
    'ui.ShowHideDonjon': 'Показать Подземелья',
    'ui.ShowHideNPC': 'Показать NPC',
    'ui.ShowHideRegion': 'Показать/скрыть названия регионов',
    'ui.ShowHideRift': 'Показать/скрыть разломы',
    'ui.DoneMarkersTitle': "Завершённые метки",
    "ui.NothingDone": "Ничего не завершено",
    'toast.MarkerNameUpdated': 'Имя маркера обновлено 💾',
    'toast.RouteNameSaved': 'Имя маршрута сохранено 💾',
    'toast.PathFinished': 'Путь завершён ✅',
    'toast.NoPath': 'Нет активного пути',
    'toast.NoPathToDelete' : 'Нет путей для удаления',
    'toast.LoadingMap': 'Загрузка карты...',
    'toast.SaveState': '● Сохранено',
    'toast.UnsaveState': '● Не сохранено',
    'toast.SaveMarkerAndRoute': 'Маркеры и маршруты сохранены локально 💾',
    'toast.FullMapDataImported': 'Все данные импортированы ✅',
    'toast.PathImported': 'Пути импортированы ✅',
    'toast.MarkerImported': 'Маркеры импортированы ✅',
    'toast.WarnDeleteAllPath': 'Вы действительно хотите удалить все пути с этой карты?',
    'toast.AllPathDeleted': 'Все пути удалены 🧹',
    'toast.MarkerMapCleared': 'Маркеры удалены для этой карты 🧹',
    'toast.CantLoadData': 'Не удалось загрузить данные пользователя:',
    'toast.CantSaveData': 'Не удалось сохранить данные локально:',
    'toast.PathInProgress': 'Путь в процессе…',
    'toast.ExportAll': 'Все данные сохранены 💾',
    'toast.MarkerDeleted': 'Метка удалена 🗑️',
    'toast.RouteDeleted': 'Маршрут удалён 🧹',
    'toast.ShareUrlCopied': 'Ссылка для обмена скопирована в буфер обмена 📋',
    'toast.SharedMerged': 'Общие маркеры и маршруты добавлены на вашу карту ✅',
    'toast.SharedTargetMissing': 'Исходная карта не найдена. Возможно, она была переименована или удалена ❌',
    'ui.ShareMapButton': 'Поделиться моей картой',
    'ui.SharedViewLabel': 'Общая карта (только просмотр)',
    'ui.SharedTargetLabel': 'Добавить на карту:',
    'ui.SharedMergeButton': 'Добавить на мою карту',
    'ui.MergeRoutesButton': 'Добавить общие данные на мою карту',
    'ui.PathNamePlaceholder': 'Название пути (необязательно)',
    'ui.MarkerNamePlaceholder': 'Имя / заметка',
    'toast.WarnDeleteAllMarkers': 'Вы действительно хотите удалить все маркеры с этой карты?',
    'toast.NothingToShare': 'Нет маршрутов или общих меток. Отметьте «Общий», чтобы добавить их в ссылку!',
    'ui.SearchLocationPlaceholder': 'Искать локацию или введите / для поиска меток...',
    "ui.region":  "Регион",
    "ui.rift":    "Разлом",
    "ui.dungeon": "Подземелье",
    "ui.annouce": "Создайте свой собственный опыт",
    "character.NewCharacter": "Создать нового персонажа",
    "character.Edit": "Редактировать",
    "confirmDeleteCharacter": "Удалить персонажа «{name}»?",
    "KeepOneCharacter": "Вы должны оставить как минимум одного персонажа.",
    "character.CreateButton": "Создать",
    "ui.NewCharacter": "Новый персонаж",
    "ui.RenameCharacter": "Переименовать персонажа",
    "ui.CharacterNamePlaceHolder": "Имя персонажа",
    "ui.MaxLimitCharacter": "Вы не можете иметь более 10 персонажей.",
    "ui.ShowAllMarker": "Показать всё",
    "toast.MarkerFiltered": "Метка добавлена в «{cat}» (сейчас отфильтрована)",
    "ui.DeleteNoteButton": "Удалить все заметки",
    "ui.DeleteNoteConfirm": "Удалить все региональные заметки? Это действие необратимо.",
    "ui.NoteList": "Список заметок",
    "toast.NoteDeleted": "Заметка удалена 🗑️",
    "toast.NoteSaved": "Заметка сохранена 💾",
    "KeyboardPan": "WASD для перемещения карты",
    "ui.ToggleSidebar": "Переключить боковую панель",
    "toast.ShareCooldown": "Пожалуйста, подождите {wait} сек перед повторным поделиться.",
    "share.tooltip": "Поделиться всей картой.",
    "character.DuplicateToggle": "Дублировать существующего персонажа",
    "character.DuplicateSourceLabel": "Персонаж для дублирования →",

    "ui.HelpLine1": "Вы можете выбрать карту в меню под мини-картой (основная или DLC)",
    "ui.Markers": "Маркеры",
    "ui.HelpLineMarker1": "Выберите Новый маркер, категорию, задайте имя и щёлкните по карте",
    "ui.Notes": "Заметки",
    "ui.HelpLineNote": "Вы можете добавлять заметки о регионах, наводя курсор на их названия",
    "ui.Routes": "Маршруты",
    "ui.HelpLineRoute1": "Выберите Новый маршрут и щёлкните по карте для первой точки",
    "ui.HelpLineRoute2": "Удерживайте Пробел для перемещения карты. Нажмите Escape или Завершить для окончания маршрута",
    "ui.HelpLineRoute3": "Все маршруты передаются при создании ссылки",
    "ui.Share": "Поделиться",
    "ui.HelpLineShare1": "Нажмите «Поделиться моей картой», чтобы создать ссылку с вашими путями, заметками и общими маркерами",
    "ui.HelpLineShare3": "Поделитесь своим приключением и заметками о заданиях, внося вклад в более насыщенную карту сообщества.",
    "ui.HelpLineShare2": "Все пути и заметки будут переданы, но включаются только маркеры, отмеченные как «Общий»",
    "ui.HelpLineTools": "Удаление маркеров, маршрутов или заметок влияет только на активного персонажа",
    "character.AvatarLabel": "Выбрать аватар",
    "search.CustomLocalOnly": "Только пользовательские метки и заметки текущей карты",
    "ui.shrineTierNormal": "Режим Нормальный",
    "ui.shrineTierElite": "Режим Элита",
    "ui.shrineTierUltimate": "Режим Высший",
    "ui.DonePanel": "Панель выполненного",
    "ui.shrineTotal": "Завершённые святыни",
    "ui.DeleteShrineButton": "Сбросить все святилища",
    "ui.ConfirmResetShrines": "Сбросить все святилища для этого персонажа?",
    "toast.ShrinesReset": "Святилища были сброшены для этого персонажа.",
    "ui.shrine": "Святилище",
    "ui.readOnlyMessage": "Режим только для чтения. Чтобы вернуться в обычный режим",
    "ui.readOnlyMessageLink": "нажмите здесь",
    "ui.linkMarker": "Поделиться маркером",
    "ui.linkRoute": "Поделиться маршрутом",


  },

    it: {
      'ui.NewMarkerTitle': 'Nuovo marcatore',
      'ui.GeneralMarker': 'Segnaposto personale',
      'ui.QuestMarker': 'Missione',
      'ui.BossMarker': 'Boss',
      'ui.LootMarker': 'Bottino',
      'ui.WaypointMarker': 'Passaggio',
      'ui.DonjonMarker': 'Sotterraneo',
      'ui.NPCMarker': 'NPC',
      'ui.ToolsTitle': 'Strumenti',
      'ui.RoutesList': 'Elenco dei percorsi',
      'ui.MarkerList': 'Elenco dei marcatori',
      'ui.Done': 'Fatto',
      'ui.AddMarkerButton': 'Aggiungi',
      "ui.CancelMarkerButton": "Annulla",
      'ui.NewPathTitle': 'Nuovo percorso',
      'ui.PathHelper': 'Tieni premuta la barra spaziatrice per spostare la mappa mentre disegni il percorso',
      'ui.AddRouteButton': 'Aggiungi',
      'ui.FinishPath': 'Termina',
      'ui.LockMarker': 'Blocca marcatori',
      'ui.ImportExportHelper': "Usa importazione/esportazione solo se cambi browser o computer. Per il salvataggio normale, usa il pulsante nell’intestazione.",
      'ui.ImportButton': 'Importa salvataggio',
      'ui.ExportButton': 'Esporta salvataggio',
      'ui.SaveTitle': 'Salva',      
      'ui.DeleteMarkerButton': 'Rimuovi tutti i marcatori',
      'ui.DeletePathButton': 'Elimina tutti i percorsi',
      'ui.Help': 'Come usare',
      'ui.HelpTitle': 'Guida',
      'ui.DeleteButton': 'Elimina',
      'ui.CenterOnMap': 'Centra sulla mappa',
      'ui.ShowHideGeneral': 'Mostra segnaposti personali',
      'ui.ShowHideQuest': 'Mostra Missioni',
      'ui.ShowHideBoss': 'Mostra Boss',
      'ui.ShowHideLoot': 'Mostra Bottino',
      'ui.ShowHideWaypoint': 'Mostra Passaggio',
      'ui.ShowHideDonjon': 'Mostra Sotterranei',
      'ui.ShowHideNPC': 'Mostra NPC',
      'ui.ShowHideRegion': 'Mostra nomi regione',
      'ui.ShowHideRift': 'Mostra fenditure',
      'ui.DoneMarkersTitle': "Marcatori completati",
      "ui.NothingDone": "Niente completato", 
      'ui.MarkerNamePlaceholder': 'Nome / nota',
      'toast.MarkerNameUpdated': 'Nome del marcatore aggiornato 💾',
      'toast.RouteNameSaved': 'Nome del percorso salvato 💾',
      'toast.PathFinished': 'Percorso completato ✅',
      'toast.NoPath': 'Nessun percorso attivo',
      "toast.NoPathToDelete": "Non ci sono percorsi da eliminare",
      'toast.LoadingMap': 'Caricamento mappa...',
      'toast.SaveState': '● Salvato',
      'toast.UnsaveState': '● Non salvato',
      'toast.SaveMarkerAndRoute': 'Marcatori e percorsi salvati localmente 💾',
      'toast.FullMapDataImported': 'Dati completi importati ✅',
      'toast.PathImported': 'Percorsi importati ✅',
      'toast.MarkerImported': 'Marcatori importati ✅',
      'toast.WarnDeleteAllPath': 'Vuoi davvero eliminare tutti i percorsi da questa mappa?',
      'toast.AllPathDeleted': 'Tutti i percorsi eliminati 🧹',
      'toast.MarkerMapCleared': 'Marcatori eliminati per questa mappa 🧹',
      'toast.CantLoadData': 'Impossibile caricare i dati utente:',
      'toast.CantSaveData': 'Impossibile salvare i dati localmente:',
      'toast.PathInProgress': 'Percorso in corso…',
      'toast.ExportAll': 'Tutti i dati sono stati salvati 💾',
      'toast.MarkerDeleted': 'Marcatore eliminato 🗑️',
      'toast.RouteDeleted': 'Percorso eliminato 🧹',
      'toast.ShareUrlCopied': 'Link di condivisione copiato negli appunti 📋',
      'toast.SharedMerged': 'Marcatori e percorsi condivisi aggiunti alla tua mappa ✅',
      'toast.SharedTargetMissing': 'Mappa originale non trovata. Potrebbe essere stata rinominata o eliminata ❌',
      'ui.MergeRoutesButton': 'Aggiungi la condivisione alla mia mappa',
      'ui.ShareMapButton': 'Condividi la mia mappa',
      'ui.SharedViewLabel': 'Mappa condivisa (solo lettura)',
      'ui.SharedTargetLabel': 'Aggiungi alla mappa:',
      'ui.SharedMergeButton': 'Aggiungi alla mia mappa',
      'ui.PathNamePlaceholder': 'Nome del percorso (facoltativo)',
      'ui.MarkerNamePlaceholder': 'Nome / nota',
      'toast.WarnDeleteAllMarkers': 'Vuoi davvero eliminare tutti i marcatori da questa mappa?',
      'toast.NothingToShare': 'Nessun percorso o marcatore condiviso. Seleziona “Condiviso” per includerli nel link!',
      'ui.SearchLocationPlaceholder': 'Cerca una posizione o digita / per cercare i marker...',
      "ui.region":  "Regione",
      "ui.rift":    "Varco",
      "ui.dungeon": "Dungeon",
      "ui.annouce": "Crea la tua esperienza personale",
      "character.NewCharacter": "Crea un nuovo personaggio",
      "character.Edit": "Modifica",
      "confirmDeleteCharacter": "Eliminare il personaggio \"{name}\"?",
      "character.CreateButton": "Crea",
      "ui.NewCharacter": "Nuovo personaggio",
      "ui.RenameCharacter": "Rinomina il tuo personaggio",
      "ui.CharacterNamePlaceHolder": "Nome del personaggio",
      "KeepOneCharacter": "Devi mantenere almeno un personaggio.",
       "ui.MaxLimitCharacter": "Non puoi avere più di 10 personaggi.",
       "ui.ShowAllMarker": "Mostra tutto",
       "toast.MarkerFiltered": "Indicatore aggiunto a \"{cat}\" (attualmente filtrato)",
       "ui.DeleteNoteButton": "Elimina tutte le note",
      "ui.DeleteNoteConfirm": "Eliminare tutte le note della regione? Questa azione è irreversibile.",
      "ui.NoteList": "Elenco delle note",
      "toast.NoteDeleted": "Nota eliminata 🗑️",
      "toast.NoteSaved": "Nota salvata 💾",
      "KeyboardPan": "WASD per muovere la mappa",
      "ui.ToggleSidebar": "Attiva/disattiva barra laterale",
      "toast.ShareCooldown": "Attendi {wait}s prima di condividere di nuovo.",
      "share.tooltip": "Condividi la mappa completa.",
      "character.DuplicateToggle": "Duplica un personaggio esistente",
      "character.DuplicateSourceLabel": "Personaggio da duplicare →",

      "ui.HelpLine1": "Puoi selezionare una mappa dal menu sotto la minimappa (principale o DLC)",
      "ui.Markers": "Segnalini",
      "ui.HelpLineMarker1": "Seleziona Nuovo segnalino, scegli una categoria, assegnagli un nome e clicca sulla mappa",
      "ui.Notes": "Note",
      "ui.HelpLineNote": "Puoi aggiungere note di regione passando il cursore sui nomi delle regioni",
      "ui.Routes": "Percorsi",
      "ui.HelpLineRoute1": "Seleziona Nuovo percorso e fai clic sulla mappa per il primo punto",
      "ui.HelpLineRoute2": "Tieni premuta la Barra spaziatrice per muovere la mappa. Premi Esc o Fine per completare",
      "ui.HelpLineRoute3": "Tutti i percorsi vengono condivisi quando generi un link",
      "ui.Share": "Condividi",
      "ui.HelpLineShare1": "Clicca su «Condividi la mia mappa» per generare un link contenente i tuoi percorsi, le tue note e i tuoi marcatori condivisi",
      "ui.HelpLineShare2": "Tutti i percorsi e le note vengono condivisi, ma solo i marcatori contrassegnati come «Condiviso» sono inclusi",
      "ui.HelpLineShare3": "Condividi la tua avventura e le tue note sulle missioni, contribuendo a una mappa comunitaria più ricca.",
      "ui.HelpLineTools": "La cancellazione di segnalini, percorsi o note influisce solo sul personaggio attivo",
      "character.AvatarLabel": "Scegli un avatar",
      "search.CustomLocalOnly": "Solo marcatori e note personalizzati della mappa attuale",
      "ui.shrineTierNormal": "Modalità Normale",
      "ui.shrineTierElite": "Modalità Élite",
      "ui.shrineTierUltimate": "Modalità Suprema",
      "ui.DonePanel": "Pannello completati",
      "ui.shrineTotal": "Santuari completati",
      "ui.DeleteShrineButton": "Reimposta tutti i santuari",
      "ui.ConfirmResetShrines": "Reimpostare tutti i santuari per questo personaggio?",
      "toast.ShrinesReset": "I santuari sono stati reimpostati per questo personaggio.",
      "ui.shrine": "Santuario",
      "ui.readOnlyMessage": "Vista in sola lettura. Per tornare alla modalità normale",
      "ui.readOnlyMessageLink": "clicca qui",
      "ui.linkMarker": "Condividi marcatore",
      "ui.linkRoute": "Condividi percorso",

    },

    zh: {
      'ui.NewMarkerTitle': '新标记',
      'ui.GeneralMarker': '个人标记',
      'ui.QuestMarker': '任务',
      'ui.BossMarker': '首领',
      'ui.LootMarker': '战利品',
      'ui.WaypointMarker': '通道',
      'ui.DonjonMarker': '地下城',
      'ui.NPCMarker': 'NPC',
      'ui.ToolsTitle': '工具',
      'ui.RoutesList': '路线列表',
      'ui.MarkerList': '标记列表',
      'ui.Done': '完成',
      'ui.AddMarkerButton': '添加',
      "ui.CancelMarkerButton": "取消",
      'ui.NewPathTitle': '新路线',
      'ui.PathHelper': '在绘制路线时按住空格键可拖动地图',
      'ui.AddRouteButton': '添加',
      'ui.FinishPath': '完成',
      'ui.LockMarker': '锁定标记',
      'ui.ImportExportHelper': '仅在更换浏览器或计算机时需要导入或导出。正常保存请使用顶部按钮。',
      'ui.ImportButton': '导入保存',
      'ui.ExportButton': '导出保存',
      'ui.SaveTitle': '保存',
      'ui.DeleteMarkerButton': '删除所有标记',
      'ui.DeletePathButton': '删除所有路线',
      'ui.Help': '使用说明',
      'ui.HelpTitle': '帮助',
      'ui.DeleteButton': '删除',
      'ui.CenterOnMap': '居中显示地图',
      'ui.ShowHideGeneral': '显示个人标记',
      'ui.ShowHideQuest': '显示任务标记',
      'ui.ShowHideBoss': '显示首领标记',
      'ui.ShowHideLoot': '显示战利品标记',
      'ui.ShowHideWaypoint': '显示通道',
      'ui.ShowHideDonjon': '显示地下城标记',
      'ui.ShowHideNPC': '显示NPC标记',
      'ui.ShowHideRegion': '显示/隐藏区域名称',
      'ui.ShowHideRift': '显示/隐藏裂隙',
      'ui.DoneMarkersTitle': "已完成的标记",
      "ui.NothingDone": "没有完成的标记",
      'toast.MarkerNameUpdated': '标记名称已更新 💾',
      'toast.RouteNameSaved': '路线名称已保存 💾',
      'toast.PathFinished': '路线已完成 ✅',
      'toast.NoPath': '当前无路线',
      'toast.NoPathToDelete' : '没有可删除的路线',
      'toast.LoadingMap': '正在加载地图...',
      'toast.SaveState': '● 已保存',
      'toast.UnsaveState': '● 未保存',
      'toast.SaveMarkerAndRoute': '标记和路线已本地保存 💾',
      'toast.FullMapDataImported': '完整地图数据已导入 ✅',
      'toast.PathImported': '路线已导入 ✅',
      'toast.MarkerImported': '标记已导入 ✅',
      'toast.WarnDeleteAllPath': '确定要删除此地图上的所有路线吗？',
      'toast.AllPathDeleted': '此地图的所有路线已清除 🧹',
      'toast.MarkerMapCleared': '此地图的标记已清除 🧹',
      'toast.CantLoadData': '无法加载用户数据：',
      'toast.CantSaveData': '无法在本地保存用户数据：',
      'toast.PathInProgress': '路线进行中…',
      'toast.ExportAll': '所有数据已保存 💾',
      'toast.SharedNoNewData': '没有新的共享数据可添加 ✅',
      'toast.ShareUrlCopied': '共享链接已复制到剪贴板 📋',
      'toast.SharedMerged': '共享的标记和路线已添加到您的地图 ✅',
      'toast.SharedTargetMissing': '未找到原始地图，可能已被重命名或删除 ❌',
      'toast.MarkerDeleted': '标记已删除 🗑️',
      'toast.RouteDeleted': '路线已删除 🧹',
      'ui.ShareMapButton': '分享我的地图',
      'ui.SharedViewLabel': '共享地图（只读）',
      'ui.SharedTargetLabel': '添加到地图：',
      'ui.SharedMergeButton': '添加到我的地图',
      'ui.MergeRoutesButton': '添加共享路线到我的地图',
      'ui.PathNamePlaceholder': '路线名称（可选）',
      'ui.MarkerNamePlaceholder': '名称 / 备注',
      'toast.WarnDeleteAllMarkers': '确定要删除此地图上的所有标记吗？',
      'toast.NothingToShare': '没有路线或共享标记。勾选“共享”以将它们包含在链接中！',
      'ui.SearchLocationPlaceholder': '搜索地点或输入 / 来搜索标记…',
      "ui.region":  "地区",
      "ui.rift":    "裂隙",
      "ui.dungeon": "地下城",
      "ui.annouce": "打造属于你的独特体验",
      "character.NewCharacter": "创建新角色",
      "character.Edit": "编辑",
      "confirmDeleteCharacter": "删除角色“{name}”？",
      "KeepOneCharacter": "您必须至少保留一个角色。",
      "ui.MaxLimitCharacter": "您最多只能拥有 10 个角色。",
      "character.CreateButton": "创建",
      "ui.NewCharacter": "新角色",
      "ui.RenameCharacter": "重命名你的角色",
      "ui.CharacterNamePlaceHolder": "角色名称",
      "ui.ShowAllMarker": "显示全部",
      "toast.MarkerFiltered": "标记已添加到“{cat}”（当前被过滤）",
      "ui.DeleteNoteButton": "删除所有笔记",
      "ui.DeleteNoteConfirm": "确定要删除所有地区笔记吗？此操作无法撤销。",
      "ui.NoteList": "笔记列表",
      "toast.NoteDeleted": "笔记已删除 🗑️",
      "toast.NoteSaved": "笔记已保存 💾",
      "KeyboardPan": "按 W、A、S、D 移动地图",
      "ui.ToggleSidebar": "切换侧边栏",
      "toast.ShareCooldown": "请等待 {wait} 秒后再分享。",
      "share.tooltip": "分享完整地图。",
      "character.DuplicateToggle": "复制现有角色",
      "character.DuplicateSourceLabel": "要复制的角色 →",

      "ui.HelpLine1": "您可以在小地图下方的下拉菜单中选择地图（主地图或DLC）",
      "ui.Markers": "标记",
      "ui.HelpLineMarker1": "选择“新标记”，选择类别、命名，然后点击地图放置标记",
      "ui.Notes": "备注",
      "ui.HelpLineNote": "将鼠标悬停在区域名称上即可添加区域备注",
      "ui.Routes": "路线",
      "ui.HelpLineRoute1": "选择“新路线”，在地图上点击以放置第一个点，然后继续绘制",
      "ui.HelpLineRoute2": "按住空格键可在绘制路线时移动地图。按 Escape 或“完成”按钮结束路线",
      "ui.HelpLineRoute3": "生成共享链接时，所有路线都会被共享",
      "ui.Share": "分享",
      "ui.HelpLineShare1": "点击“分享我的地图”即可生成一个包含你的路线、笔记和共享标记的链接",
      "ui.HelpLineShare2": "所有路线和笔记都会被分享，但只有勾选“共享”的标记才会被包含",
      "ui.HelpLineShare3": "分享你的冒险与任务笔记，为更丰富的社区地图贡献力量。",
      "ui.HelpLineTools": "在工具栏中删除标记、路线或备注只会影响当前角色",
      "character.AvatarLabel": "选择头像",
      "search.CustomLocalOnly": "仅显示当前地图的自定义标记和备注",
      "ui.shrineTierNormal": "普通难度",
      "ui.shrineTierElite": "精英难度",
      "ui.shrineTierUltimate": "终极难度",
      "ui.DonePanel": "完成面板",
      "ui.shrineTotal": "已完成的神龛",      
      "ui.DeleteShrineButton": "重置所有神龛",
      "ui.ConfirmResetShrines": "要为此角色重置所有神龛吗？",
      "toast.ShrinesReset": "已为此角色重置所有神龛。",
      "ui.shrine": "祭坛",
      "ui.readOnlyMessage": "只读模式。要返回正常模式",
      "ui.readOnlyMessageLink": "请点击这里",
      "ui.linkMarker": "分享标记",
      "ui.linkRoute": "分享路线",

    },
    ja: {
        'ui.NewMarkerTitle': '新しいマーカー',
      'ui.GeneralMarker': '一般',
      'ui.QuestMarker': 'クエスト',
      'ui.BossMarker': 'ボス',
      'ui.LootMarker': '戦利品',
      'ui.WaypointMarker': '通路',
      'ui.DonjonMarker': 'ダンジョン',
      'ui.NPCMarker': 'NPC',
      'ui.ToolsTitle': 'ツール',
      'ui.RoutesList': 'ルート一覧',
      'ui.MarkerList': 'マーカー一覧',
      'ui.Done': '完了',
      'ui.AddMarkerButton': '追加',
      "ui.CancelMarkerButton": "キャンセル",
      'ui.NewPathTitle': '新しいルート',
      'ui.PathHelper': 'ルート描画中にスペースキーを押し続けると、マップをドラッグできます',
      'ui.AddRouteButton': '追加',
      'ui.FinishPath': '終了',
      'ui.LockMarker': 'マーカーをロック',
      'ui.ImportExportHelper': '別のブラウザや別のPCに移行する場合のみインポート / エクスポートが必要です。通常の保存にはヘッダーの保存ボタンを使ってください。',
      'ui.ImportButton': 'セーブをインポート',
      'ui.ExportButton': 'セーブをエクスポート',
      'ui.SaveTitle': '保存',
      'ui.DeleteMarkerButton': 'すべてのマーカーを削除',
      'ui.DeletePathButton': 'すべてのルートを削除',
      'ui.Help': '使い方',
      'ui.HelpTitle': 'ヘルプ',
      'ui.DeleteButton': '削除',
      'toast.MarkerNameUpdated': 'マーカー名を保存しました 💾',
      'toast.RouteNameSaved': 'ルート名を保存しました 💾',
      'toast.PathFinished': 'ルートを完了しました ✅',
      'toast.NoPath': '現在のルートはありません',
      'toast.NoPathToDelete': '削除するルートがありません',
      'toast.LoadingMap': 'マップを読み込み中…',
      'toast.SaveState': '● 保存済み',
      'toast.UnsaveState': '● 未保存',
      'toast.SaveMarkerAndRoute': 'マーカーとルートをローカルに保存しました 💾',
      'toast.FullMapDataImported': 'マップデータをすべてインポートしました ✅',
      'toast.PathImported': 'ルートをインポートしました ✅',
      'toast.MarkerImported': 'マーカーをインポートしました ✅',
      'toast.WarnDeleteAllPath': '本当にこのマップのすべてのルートを削除しますか？',
      'toast.AllPathDeleted': 'このマップのルートをすべて削除しました 🧹',
      'toast.MarkerMapCleared': 'このマップのマーカーをすべて削除しました 🧹',
      'toast.CantLoadData': 'ユーザーデータを読み込めませんでした：',
      'toast.CantSaveData': 'ユーザーデータをローカルに保存できませんでした：',
      'toast.PathInProgress': 'ルート作成中…',
      'toast.ExportAll': 'すべてのデータを保存しました 💾',
      'toast.SharedNoNewData': '共有マップから追加する新しいデータはありません ✅',
      'toast.ShareUrlCopied': '共有リンクをクリップボードにコピーしました 📋',
      'toast.SharedMerged': '共有されたマーカーとルートをマップに追加しました ✅',
      'toast.SharedTargetMissing': '元のマップが見つかりません。名前が変更されたか削除された可能性があります ❌',
      'toast.MarkerDeleted': 'マーカーを削除しました 🗑️',
      'toast.RouteDeleted': 'ルートを削除しました 🧹',
      'ui.ShowHideGeneral': '個人マーカーを表示',
      "ui.ShowHideQuest": "クエストマーカーを表示",
      "ui.ShowHideBoss": "ボスマーカーを表示",
      "ui.ShowHideLoot": "戦利品マーカーを表示",
      'ui.ShowHideWaypoint': '通路を表示',
      "ui.ShowHideDonjon": "ダンジョンマーカーを表示",
      "ui.ShowHideNPC": "NPCマーカーを表示",
      'ui.DoneMarkersTitle': '完了したマーカー',
      'ui.NothingDone': '完了したマーカーはありません',
      'ui.ShowHideRegion': '地域名の表示 / 非表示',
      'ui.ShowHideRift': 'リフトの表示 / 非表示',
      'ui.CenterOnMap': 'マップの中心に移動',
      'ui.ShareMapButton': 'マイマップを共有',
      'ui.SharedViewLabel': '共有マップ（閲覧のみ）',
      'ui.SharedTargetLabel': '追加先マップ：',
      'ui.SharedMergeButton': 'マイマップに追加',
      'ui.MergeRoutesButton': '共有ルートをマイマップに追加',
      'ui.PathNamePlaceholder': 'ルート名（任意）',
      'ui.MarkerNamePlaceholder': '名前 / メモ',
      'toast.WarnDeleteAllMarkers': '本当にこのマップのすべてのマーカーを削除しますか？',
      'toast.NothingToShare': '共有できるものがありません（ルートまたは共有マーカーがありません）',
      'ui.SearchLocationPlaceholder': '場所を検索、または「/」を入力してマーカーを検索…',
      'ui.region':  '地域',
      'ui.rift':    'リフト',
      'ui.dungeon': 'ダンジョン',
      "ui.annouce": "自分だけの体験を築こう",
      "character.NewCharacter": "新しいキャラクターを作成",
      "character.Edit": "編集",
      "confirmDeleteCharacter": "キャラクター「{name}」を削除しますか？",
      "KeepOneCharacter": "最低でも1人のキャラクターを残す必要があります。",
      "character.CreateButton": "作成",
      "ui.NewCharacter": "新しいキャラクター",
      "ui.RenameCharacter": "キャラクター名を変更",
      "ui.CharacterNamePlaceHolder": "キャラクター名",
      "ui.MaxLimitCharacter": "キャラクターは10人までしか作成できません。",
      "ui.ShowAllMarker": "すべて表示",
      "toast.MarkerFiltered": "「{cat}」にマーカーを追加しました（現在フィルター中）",
      "ui.DeleteNoteButton": "すべてのメモを削除",
      "ui.DeleteNoteConfirm": "すべての地域メモを削除しますか？ この操作は元に戻せません。",
      "ui.NoteList": "ノート一覧",
      "toast.NoteDeleted": "ノートを削除しました 🗑️",
      "toast.NoteSaved": "ノートを保存しました 💾",
      "KeyboardPan": "WASD でマップを移動",
      "ui.ToggleSidebar": "サイドバーを切り替え",
      "toast.ShareCooldown": "{wait}秒待ってから再度共有してください。",
      "share.tooltip": "マップ全体を共有します。",
      "character.DuplicateToggle": "既存のキャラクターを複製する",
      "character.DuplicateSourceLabel": "複製するキャラクター →",

      "ui.HelpLine1": "ミニマップ下のドロップダウンからマップを選択できます（メインまたはDLC）",
      "ui.Markers": "マーカー",
      "ui.HelpLineMarker1": "「新しいマーカー」を選択し、カテゴリと名前を設定してから地図をクリックします",
      "ui.Notes": "ノート",
      "ui.HelpLineNote": "地域名にカーソルを合わせることで、その地域にメモを追加できます",
      "ui.Routes": "ルート",
      "ui.HelpLineRoute1": "「新しいルート」を選択し、地図をクリックして最初のポイントを置きます",
      "ui.HelpLineRoute2": "ルート描画中はスペースキーで地図を移動できます。Escape または完了ボタンで終了します",
      "ui.HelpLineRoute3": "共有リンクを生成すると、すべてのルートが共有されます",
      "ui.Share": "共有",
      "ui.HelpLineShare1": "「マップを共有」をクリックすると、あなたのルート、ノート、共有マーカーを含むリンクが生成されます",
      "ui.HelpLineShare2": "すべてのルートとノートは共有されますが、「共有」としてチェックされたマーカーのみが含まれます",
      "ui.HelpLineShare3": "あなたの冒険とクエストメモを共有し、より充実したコミュニティマップ作りに貢献しましょう。",
      "ui.HelpLineTools": "ツールでマーカー・ルート・ノートを削除しても、影響するのはアクティブキャラクターのみです",
      "character.AvatarLabel": "アバターを選択",
      "search.CustomLocalOnly": "現在のマップのカスタムマーカーとノートのみを表示",
      "ui.shrineTierNormal": "ノーマルモード",
      "ui.shrineTierElite": "エリートモード",
      "ui.shrineTierUltimate": "アルティメットモード",
      "ui.DonePanel": "完了パネル",
      "ui.shrineTotal": "完了した祭壇",
      "ui.DeleteShrineButton": "すべての祠をリセット",
      "ui.ConfirmResetShrines": "このキャラクターのすべての祠をリセットしますか？",
      "toast.ShrinesReset": "このキャラクターの祠がリセットされました。",
      "ui.shrine": "聖堂",
      "ui.readOnlyMessage": "読み取り専用ビューです。通常モードに戻るには",
      "ui.readOnlyMessageLink": "こちらをクリック",
      "ui.linkMarker": "マーカーを共有",
      "ui.linkRoute": "ルートを共有",

    }

  };


    // --- API i18n de base ----------------------------------

  function setLang(lang) {
    if (!translations[lang]) lang = 'en';
    localStorage.setItem(LANG_KEY, lang);
    applyLang(lang);
  }

  function getLang() {
    return localStorage.getItem(LANG_KEY) || 'en';
  }

  function applyLang(lang) {
    const dict = translations[lang] || translations.en;

    // texte
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (dict[key]) el.textContent = dict[key];
    });

    // placeholder
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
      const key = el.getAttribute('data-i18n-placeholder');
      if (dict[key]) el.setAttribute('placeholder', dict[key]);
    });

    // title
    document.querySelectorAll('[data-i18n-title]').forEach(el => {
      const key = el.getAttribute('data-i18n-title');
      if (dict[key]) el.setAttribute('title', dict[key]);
    });

    // tooltip
    document.querySelectorAll('[data-i18n-tooltip]').forEach(el => {
      const key = el.getAttribute('data-i18n-tooltip');
      if (dict[key]) el.setAttribute('data-tooltip', dict[key]);
    });
  }


  function t(key, params = {}) {
    const lang = getLang();
    const dict = translations[lang] || translations.en;
    let text = dict[key] || key;

    // Interpolation {variable}
    for (const p in params) {
      const reg = new RegExp(`{${p}}`, 'g');
      text = text.replace(reg, params[p]);
    }

    return text;
  }

  // --- Helpers génériques pour les dropdowns custom ---------------------

  function initCustomDropdown({
    nativeId,
    dropdownId,
    itemSelector = '.option-item',
    valueAttr = 'data-value',
    currentButtonSelector = '.select-current',
    currentLabelSelector = '.select-label',
    defaultValue = '',
    getLabel,
    extraSync,
  }) {
    const nativeSelect = document.getElementById(nativeId);
    const dropdown = document.getElementById(dropdownId);
    if (!nativeSelect || !dropdown) return;

    initCustomDropdownForElements({
      nativeSelect,
      dropdown,
      itemSelector,
      valueAttr,
      currentButtonSelector,
      currentLabelSelector,
      defaultValue,
      getLabel,
      extraSync,
    });
  }

  // Variante qui prend directement les éléments (pratique pour la liste des marqueurs)
  function initCustomDropdownForElements({
    nativeSelect,
    dropdown,
    itemSelector = '.option-item',
    valueAttr = 'data-value',
    currentButtonSelector = '.select-current',
    currentLabelSelector = '.select-label',
    defaultValue = '',
    getLabel,
    extraSync,
  }) {
    if (!nativeSelect || !dropdown) return;

    const currentBtn = dropdown.querySelector(currentButtonSelector);
    const currentLabel = currentLabelSelector
      ? dropdown.querySelector(currentLabelSelector)
      : null;
    const items = dropdown.querySelectorAll(itemSelector);
    if (!currentBtn || !items.length) return;

    function syncFromSelect() {
      const value = nativeSelect.value || defaultValue;
      const item = dropdown.querySelector(`${itemSelector}[${valueAttr}="${value}"]`);
      if (!item) return;

      if (currentLabel) {
        const labelText = getLabel
          ? getLabel(item, value)
          : (item.textContent || '').trim();
        currentLabel.textContent = labelText;
      }

      if (typeof extraSync === 'function') {
        extraSync({ currentBtn, item, value });
      }
    }

    // Ouverture / fermeture
    currentBtn.addEventListener('click', (e) => {
      e.stopPropagation();
      dropdown.classList.toggle('open');
    });

    document.addEventListener('click', () => {
      dropdown.classList.remove('open');
    });

    // Clic sur une option
    items.forEach(btn => {
      btn.addEventListener('click', () => {
        const value = btn.getAttribute(valueAttr);
        if (!value) return;

        nativeSelect.value = value;
        nativeSelect.dispatchEvent(new Event('change'));

        syncFromSelect();
        dropdown.classList.remove('open');
      });
    });

    // Sync quand le <select> change (via code ou UI)
    nativeSelect.addEventListener('change', syncFromSelect);

    syncFromSelect();
  }

  // --- Exposition globale -----------------------------------------------

  window.GDMMLang = { setLang, getLang, applyLang, t };
  window.initCustomDropdown = initCustomDropdown;
  window.initCustomDropdownForElements = initCustomDropdownForElements;

  // --- Initialisation langue + dropdown de langue -----------------------

  document.addEventListener('DOMContentLoaded', () => {
    const current = getLang();
    applyLang(current);

    const nativeSelect = document.getElementById('langSelect');
    if (!nativeSelect) return;

    nativeSelect.value = current;

    // Quand l'utilisateur change la langue
      nativeSelect.addEventListener('change', (e) => {
        const lang = e.target.value || 'en';
        setLang(lang); // setLang refait applyLang

        if (window.UiCore) {
          // remet les markers sur la map
          if (typeof UiCore.renderMarkers === 'function') {
            UiCore.renderMarkers({ skipRoutesPanel: true });
          }
          // remet la liste des marqueurs avec la bonne langue
          if (typeof UiCore.renderList === 'function') {
            UiCore.renderList();
          }
        }

        // resynchronise le dropdown "Nouveau marqueur"
        const newCat = document.getElementById('newCategory');
        if (newCat) {
          newCat.dispatchEvent(new Event('change'));
        }
          if (typeof window.refreshCharacterDropdown === 'function') {
            window.refreshCharacterDropdown();
          }
      });


    // Dropdown custom "flags"
    initCustomDropdown({
      nativeId: 'langSelect',
      dropdownId: 'langDropdown',
      itemSelector: '.option-item',
      valueAttr: 'data-lang',
      currentButtonSelector: '.select-current',
      currentLabelSelector: '.lang-label',
      defaultValue: 'en',
      getLabel: (item) => {
        const span = item.querySelector('span:last-child');
        return span ? span.textContent : (item.textContent || '').trim();
      },
      extraSync: ({ currentBtn, item }) => {
        const currentFlag = currentBtn.querySelector('.flag');
        const itemFlag    = item.querySelector('.flag');
        if (!currentFlag || !itemFlag) return;

        const flagClass = Array.from(itemFlag.classList)
          .find(c => c.startsWith('flag-') && c !== 'flag');

        if (flagClass) {
          currentFlag.className = 'flag ' + flagClass;
        }
      }
    });
  });

})();

