// ui.rift.js

window.RIFT_MARKERS_CAIRN = [
{ id: 'rift_devils_crossing', tag: 'tagRiftDevilsCrossing', xp: 63.55, yp: 89.4 },
{ id: 'rift_cower_crossing', tag: 'tagRiftLowerCrossing', xp: 65.35, yp: 83.7 },
{ id: 'rift_burrwitch_road', tag: 'tagRiftBurrwitchRoad', xp: 70.15, yp: 74.83 },
{ id: 'rift_wightmire', tag: 'tagRiftWightmire', xp: 68.63, yp: 78.32 },
{ id: 'rift_flooded_passage', tag: 'tagRiftFloodedPassage', xp: 61.96, yp: 72.86, isDungeon:true },
{ id: 'tag_rift_burrwitch_outskirts', tag: 'tagRiftBurrwitchOutskirts', xp: 67.8, yp: 71.3 },
{ id: 'rift_burrwitch_village', tag: 'tagRiftBurrwitchVillage', xp: 68.1, yp: 64.7 },
{ id: 'tift_wardens_cellar', tag: 'tagRiftWardensCellar', xp: 63.78, yp: 53.27, isDungeon:true },
{ id: 'rift_wardens_labratory01', tag: 'tagRiftWardensLabratory01', xp: 60.01, yp: 52.70, isDungeon:true },
{ id: 'rift_wardens_labratory02', tag: 'tagRiftWardensLabratory02', xp: 64.09, yp: 49.17, isDungeon:true },
{ id: 'rift_broken_hills', tag: 'tagRiftBrokenHills', xp: 49.43, yp: 82.6 },
{ id: 'rift_old_arkovia', tag: 'tagRiftOldArkovia', xp: 52.37, yp: 78.4 },
{ id: 'rift_arkovian_foothills', tag: 'tagRiftArkovianFoothills', xp: 54.5, yp: 85.9 },
{ id: 'rift_cronleys_hideout', tag: 'tagRiftCronleysHideout', xp: 54.35, yp: 69.45, isDungeon:true },
{ id: 'rift_twin_falls', tag: 'tagRiftTwinFalls', xp: 48.6, yp: 77.4 },
{ id: 'rift_smugglers_pass', tag: 'tagRiftSmugglersPass', xp: 27.84, yp: 85.10, isDungeon:true },
{ id: 'rift_smugglers_road', tag: 'tagRiftSmugglersRoad', xp: 37.25, yp: 68.9 },
{ id: 'tag_rift_jaggedWaste', tag: 'tagRiftJaggedWaste', xp: 41.29, yp: 72.48 },
{ id: 'rift_deadmans_gulch', tag: 'tagRiftDeadmansGulch', xp: 31.9, yp: 77.48 },
{ id: 'tag_rift_homestead', tag: 'tagRiftHomestead', xp: 37.4, yp: 64.22 },
{ id: 'rift_rotted_croplands', tag: 'tagRiftRottedCroplands', xp: 30.3, yp: 68.5 },
{ id: 'gloomwald_entrance', tag: 'tagGDX1RiftGloomwaldEntrance', xp: 73.2, yp: 56.1 },
{ id: 'gloomwald_river_crossing', tag: 'tagGDX1RiftGloomwaldRiverCrossing', xp: 74.8, yp: 47.78 },
{ id: 'rift_ugdenbog_coven', tag: 'tagGDX1RiftUgdenbogCoven', xp: 83.77, yp: 47.1 },
{ id: 'ugdenbog_center', tag: 'tagGDX1RiftUgdenbogCenter', xp: 87.53, yp: 38.1 },
{ id: 'ugdenbog_village', tag: 'tagGDX1RiftUgdenbogVillage', xp: 84.2, yp: 29.9 },
{ id: 'alpine_gate', tag: 'tagRiftAlpineGate', xp: 18.95, yp: 41.86 },
{ id: 'alpine_road', tag: 'tagRiftAlpineRoad', xp: 12.73, yp: 36.3 },
{ id: 'alpine_valley', tag: 'tagRiftAlpineValley', xp: 8.08, yp: 30.95 },
{ id: 'alpine_fort', tag: 'tagRiftAlpineFort', xp: 14.88, yp: 22.9 },
{ id: 'necropolis_gate', tag: 'tagRiftNecropolisGate', xp: 22.5, yp: 15.25 },
{ id: 'necropolis_interior', tag: 'tagRiftNecropolisInterior', xp: 23.55, yp: 5.6 },
{ id: 'rift_blood_grove', tag: 'tagRiftBloodGrove', xp: 30.39, yp: 51.52 },
{ id: 'dark_vale', tag: 'tagRiftDarkvale', xp: 29.59, yp: 38.38, isDungeon:true },
{ id: 'Sorrows_Bastion', tag: 'tagRiftSorrowsBastion', xp: 33.80, yp: 58.72 }


];


window.RIFT_MARKERS_MALMOUTH = [
{ id: 'rift_malmouth_aetherfire', tag: 'tagGDX1RiftMalmouthAetherfire', xp: 64.0, yp: 95.9 },
{ id: 'rift_malmouth_outskirts', tag: 'tagGDX1RiftMalmouthOutskirts', xp: 65.5, yp: 38.50 },
{ id: 'rift_malmouth_industrial', tag: 'tagGDX1RiftMalmouthIndustrial', xp: 48.5, yp: 44.47 },
{ id: 'rift_malmouth_inner', tag: 'tagGDX1RiftMalmouthInner', xp: 41.6, yp: 17.28 },
{ id: 'malmouth_sewers', tag: 'tagGDX1RiftMalmouthSewers', xp: 45.35, yp: 66.33, isDungeon:true }
    
]

window.RIFT_MARKERS_KORVAN = [
{ id: 'rift_witch_god_base', tag: 'tagGDX2RiftWitchGodBase', xp: 21.12, yp: 98.06 },
{ id: 'rift_korvan_plateau', tag: 'tagGDX2RiftKorvanPlateau', xp: 25.92, yp: 86.71 },
{ id: 'rift_temple_of_osyr', tag: 'tagGDX2RiftTempleOfOsyr', xp: 33.77, yp: 77.46 },
{ id: 'rift_korvan_sands', tag: 'tagGDX2RiftKorvanSands', xp: 27.40, yp: 57.09 },
{ id: 'rift_cairan_docks', tag: 'tagGDX2RiftCairanDocks', xp: 38.83, yp: 51.50 },
{ id: 'rift_oasis', tag: 'tagGDX2RiftOasis', xp: 53.47, yp: 52.56 },
{ id: 'rift_vanguard', tag: 'tagGDX2RiftVanguard', xp: 65.87, yp: 48.11 },
{ id: 'rift_abyd', tag: 'tagGDX2RiftAbyd', xp: 68.64, yp: 42.52 },
{ id: 'rift_infernal_wastes', tag: 'tagGDX2RiftInfernalWastes', xp: 60.82, yp: 36.08 },
{ id: 'rift_temple', tag: 'tagGDX2RiftTemple', xp: 58.11, yp: 7.50, isDungeon:true },
{ id: 'rift_korvan_city', tag: 'tagGDX2RiftKorvanCity', xp: 53.59, yp: 25.55 },
{ id: 'rift_lost_oasis', tag: 'tagGDX2RiftLostOasis', xp: 69.25, yp: 21.83,isDungeon:true },
{ id: 'tag_gDX2_rift_eldritch', tag: 'tagGDX2RiftEldritch', xp: 68.69, yp: 8.43, isDungeon:true }

]

// 2) Rift localization
window.RIFT_LABELS = {
  en: {
    "tagRiftDevilsCrossing": "Devil's Crossing Rift",
    "tagRiftLowerCrossing": "Lower Crossing Rift",
    "tagRiftBurrwitchRoad": "Foggy Bank Rift",
    "tagRiftWightmire": "Wightmire Rift",
    "tagRiftFloodedPassage": "Flooded Passage Rift",
    "tagRiftBurrwitchOutskirts": "Burrwitch Outskirts Rift",
    "tagRiftBurrwitchVillage": "Burrwitch Village Rift",
    "tagRiftWardensCellar": "Warden's Cellar Rift",
    "tagRiftWardensLabratory01": "Underground Transit Rift",
    "tagRiftWardensLabratory02": "Warden's Laboratory Rift",
    "tagRiftBrokenHills": "Broken Hills Rift",
    "tagRiftOldArkovia": "Old Arkovia Rift",
    "tagRiftArkovianFoothills": "Arkovian Foothills Rift",
    "tagRiftCronleysHideout": "Cronley's Hideout Rift",
    "tagRiftTwinFalls": "Twin Falls Rift",
    "tagRiftSmugglersPass": "Smuggler's Pass Rift",
    "tagRiftSmugglersRoad": "Prospector's Trail Rift",
    "tagRiftJaggedWaste": "Pine Barrens Rift",
    "tagRiftDeadmansGulch": "Deadman's Gulch Rift",
    "tagRiftHomestead": "Homestead Rift",
    "tagRiftRottedCroplands": "Rotting Croplands Rift",
    "tagRiftSorrowsBastion": "Sorrow's Bastion Rift",
    "tagRiftBloodGrove": "Blood Grove Rift",
    "tagRiftDarkvale": "Darkvale Gate Rift",
    "tagRiftAlpineGate": "Asterkarn Mountains Rift",
    "tagRiftAlpineRoad": "Asterkarn Road Rift",
    "tagRiftAlpineValley": "Asterkarn Valley Rift",
    "tagRiftAlpineFort": "Fort Ikon Rift",
    "tagRiftNecropolisGate": "Gates of Necropolis Rift",
    "tagRiftNecropolisInterior": "Necropolis Interior Rift",
    "tagGDX1RiftGloomwaldEntrance": "Gloomwald Rift",
    "tagGDX1RiftGloomwaldRiverCrossing": "Gloomwald Crossing Rift",
    "tagGDX1RiftUgdenbogCoven": "Coven's Refuge Rift",
    "tagGDX1RiftUgdenbogCenter": "Ugdenbog Rift",
    "tagGDX1RiftUgdenbogVillage": "Barrowholm Rift",
    "tagGDX1RiftMalmouthAetherfire": "Lone Watch Rift",
    "tagGDX1RiftMalmouthOutskirts": "Malmouth Outskirts Rift",
    "tagGDX1RiftMalmouthIndustrial": "Malmouth Steelcap District Rift",
    "tagGDX1RiftMalmouthInner": "Malmouth Crown Hill Rift",
    "tagGDX1RiftMalmouthSewers": "Malmouth Sewers Rift",
    "tagGDX2RiftWitchGodBase": "Conclave of the Three Rift",
    "tagGDX2RiftKorvanPlateau": "Korvan Plateau Rift",
    "tagGDX2RiftTempleOfOsyr": "Temple of Osyr Rift",
    "tagGDX2RiftKorvanSands": "Korvan Sands Rift",
    "tagGDX2RiftCairanDocks": "Cairan Docks Rift",
    "tagGDX2RiftOasis": "Sunbane Oasis Rift",
    "tagGDX2RiftVanguard": "Vanguard of the Three Rift",
    "tagGDX2RiftAbyd": "Ruins of Abyd Rift",
    "tagGDX2RiftInfernalWastes": "Infernal Wastes Rift",
    "tagGDX2RiftKorvanCity": "Korvan City Rift",
    "tagGDX2RiftTemple": "Tomb of the Eldritch Sun Rift",
    "tagGDX2RiftEldritch": "Eldritch Gate Rift",
    "tagGDX2RiftLostOasis": "Lost Oasis Rift"
  },
  fr: {
    "tagRiftDevilsCrossing": "Faille du Passage du Diable",
    "tagRiftLowerCrossing": "Faille du Bas Passage",
    "tagRiftBurrwitchRoad": "Faille de la Route de Burrwitch",
    "tagRiftWightmire": "Faille du Bourbier Surnaturel",
    "tagRiftFloodedPassage": "Faille du Passage Inondé",
    "tagRiftBurrwitchOutskirts": "Faille des Faubourgs de Burrwitch",
    "tagRiftBurrwitchVillage": "Faille du Village de Burrwitch",
    "tagRiftWardensCellar": "Faille de la Cave du Directeur",
    "tagRiftWardensLabratory01": "Faille du Passage Souterrain",
    "tagRiftWardensLabratory02": "Faille du Laboratoire du Directeur",
    "tagRiftBrokenHills": "Faille des Collines Brisées",
    "tagRiftOldArkovia": "Faille du Vieil Arkovia",
    "tagRiftArkovianFoothills": "Faille des Contreforts arkoviens",
    "tagRiftCronleysHideout": "Faille de la Cachette de Cronley",
    "tagRiftTwinFalls": "Faille des Chutes Jumelles",
    "tagRiftSmugglersPass": "Faille du Col du Contrebandier",
    "tagRiftSmugglersRoad": "Faille du Chemin du Prospecteur",
    "tagRiftJaggedWaste": "Faille de la Toundra aux Pins",
    "tagRiftDeadmansGulch": "Faille du Ravin du Mort",
    "tagRiftHomestead": "Faille du Domaine",
    "tagRiftRottedCroplands": "Faille des Terres en Culture Pourrissantes",
    "tagRiftSorrowsBastion": "Faille du Bastion du Chagrin",
    "tagRiftBloodGrove": "Faille du Bosquet de Sang",
    "tagRiftDarkvale": "Faille de la Porte de Valsombre",
    "tagRiftAlpineGate": "Faille des Monts Asterkarn",
    "tagRiftAlpineRoad": "Faille de la Route d'Asterkarn",
    "tagRiftAlpineValley": "Faille de la Vallée d'Asterkarn",
    "tagRiftAlpineFort": "Faille du Fort Ikon",
    "tagRiftNecropolisGate": "Faille des Portes de la Nécropole",
    "tagRiftNecropolisInterior": "Faille de la Nécropole Intérieure",
    "tagGDX1RiftGloomwaldEntrance": "Faille de Gloomwald",
    "tagGDX1RiftGloomwaldRiverCrossing": "Faille de la croisée de Gloomwald",
    "tagGDX1RiftUgdenbogCoven": "Faille du Refuge de la Bande",
    "tagGDX1RiftUgdenbogCenter": "Faille d'Ugdenbog",
    "tagGDX1RiftUgdenbogVillage": "Faille de Barrowholm",
    "tagGDX1RiftMalmouthAetherfire": "Faille du Guet Solitaire",
    "tagGDX1RiftMalmouthOutskirts": "Faille des Faubourgs de Malmouth",
    "tagGDX1RiftMalmouthIndustrial": "Faille du District de Cap-Ferré",
    "tagGDX1RiftMalmouthInner": "Faille de la Colline Couronnée",
    "tagGDX1RiftMalmouthSewers": "Faille des Égouts de Malmouth",
    "tagGDX2RiftWitchGodBase": "Faille du Conclave des Trois",
    "tagGDX2RiftKorvanPlateau": "Faille du Plateau de Korvan",
    "tagGDX2RiftTempleOfOsyr": "Faille du Temple d'Osyr",
    "tagGDX2RiftKorvanSands": "Faille des Sables de Korvan",
    "tagGDX2RiftCairanDocks": "Faille des Docks de Cairan",
    "tagGDX2RiftOasis": "Faille de l'Oasis de Fléau-Solaire",
    "tagGDX2RiftVanguard": "Faille de l'Avant-garde des Trois",
    "tagGDX2RiftAbyd": "Faille des Ruines d'Abyd",
    "tagGDX2RiftInfernalWastes": "Faille du Désert Infernal",
    "tagGDX2RiftKorvanCity": "Faille de la Cité de Korvan",
    "tagGDX2RiftTemple": "Faille du Tombeau du Soleil Inquiétant",
    "tagGDX2RiftEldritch": "Faille des Champs Astraux",
    "tagGDX2RiftLostOasis": "Faille de l'Oasis perdue"
  },
  es: {
    "tagRiftDevilsCrossing": "Grieta de Cruce del Diablo",
    "tagRiftLowerCrossing": "Grieta de Cruce Inferior",
    "tagRiftBurrwitchRoad": "Grieta de Banco Brumoso",
    "tagRiftWightmire": "Grieta de Wightmire",
    "tagRiftFloodedPassage": "Grieta de Paso Inundado",
    "tagRiftBurrwitchOutskirts": "Grieta de las Afueras de Burrwitch",
    "tagRiftBurrwitchVillage": "Grieta de Burrwitch",
    "tagRiftWardensCellar": "Grieta del Sótano del Alcaide",
    "tagRiftWardensLabratory01": "Grieta de Tránsito Subterráneo",
    "tagRiftWardensLabratory02": "Grieta del Laboratorio del Alcaide",
    "tagRiftBrokenHills": "Grieta de Colinas Quebradas",
    "tagRiftOldArkovia": "Grieta de Vieja Arkovia",
    "tagRiftArkovianFoothills": "Grieta de las Estribaciones de Arkovia",
    "tagRiftCronleysHideout": "Grieta del Escondrijo de Cronley",
    "tagRiftTwinFalls": "Grieta de las Cascadas Gemelas",
    "tagRiftSmugglersPass": "Grieta del Paso del Contrabandista",
    "tagRiftSmugglersRoad": "Grieta del Sendero del Buscador",
    "tagRiftJaggedWaste": "Grieta de Los Pinares",
    "tagRiftDeadmansGulch": "Grieta del Barranco del Hombre Muerto",
    "tagRiftHomestead": "Grieta de La Hacienda",
    "tagRiftRottedCroplands": "Grieta de las Tierras de Cultivo Pútridas",
    "tagRiftSorrowsBastion": "Grieta del Bastión del Pesar",
    "tagRiftBloodGrove": "Grieta de la Arboleda Sangrienta",
    "tagRiftDarkvale": "Portal de Valle Oscuro",
    "tagRiftAlpineGate": "Grieta de las Montañas Asterkarn",
    "tagRiftAlpineRoad": "Grieta de la Carretera Asterkarn",
    "tagRiftAlpineValley": "Grieta del Valle Asterkarn",
    "tagRiftAlpineFort": "Grieta de Fuerte Ikon",
    "tagRiftNecropolisGate": "Grieta de las Puertas de la Necrópolis",
    "tagRiftNecropolisInterior": "Grieta del Interior de la Necrópolis",
    "tagGDX1RiftGloomwaldEntrance": "Grieta de la Arboleda de la Penumbra",
    "tagGDX1RiftGloomwaldRiverCrossing": "Grieta del cruce de la Arboleda de la Penumbra",
    "tagGDX1RiftUgdenbogCoven": "Grieta del Refugio del Aquelarre",
    "tagGDX1RiftUgdenbogCenter": "Grieta de Pantano de Ugden",
    "tagGDX1RiftUgdenbogVillage": "Grieta de Islote del Túmulo",
    "tagGDX1RiftMalmouthAetherfire": "Grieta de Guardia Solitaria",
    "tagGDX1RiftMalmouthOutskirts": "Grieta de las Afueras de Malmouth",
    "tagGDX1RiftMalmouthIndustrial": "Grieta del Distrito del Acero de Malmouth",
    "tagGDX1RiftMalmouthInner": "Grieta de Colina de la Corona de Malmouth",
    "tagGDX1RiftMalmouthSewers": "Grieta de las Alcantarillas de Malmouth",
    "tagGDX2RiftWitchGodBase": "Grieta del Cónclave de los Tres",
    "tagGDX2RiftKorvanPlateau": "Grieta de la Meseta de Korvan",
    "tagGDX2RiftTempleOfOsyr": "Grieta del Templo de Osyr",
    "tagGDX2RiftKorvanSands": "Grieta de las Arenas de Korvan",
    "tagGDX2RiftCairanDocks": "Grieta de los Muelles de Cairan",
    "tagGDX2RiftOasis": "Grieta del Oasis Sunbane",
    "tagGDX2RiftVanguard": "Grieta de la Vanguardia de los Tres",
    "tagGDX2RiftAbyd": "Grieta de las Ruinas de Abyd",
    "tagGDX2RiftInfernalWastes": "Grieta de los Yermos Infernales",
    "tagGDX2RiftKorvanCity": "Grieta de la Ciudad de Korvan",
    "tagGDX2RiftTemple": "Grieta de la Tumba del Sol Sobrenatural",
    "tagGDX2RiftEldritch": "Grieta de la Puerta Sobrenatural",
    "tagGDX2RiftLostOasis": "Grieta del Oasis Perdido"
  },
  pt:{
    "tagRiftDevilsCrossing": "Portal do Cruzamento do Diabo",
    "tagRiftLowerCrossing": "Portal do Cruzamento Inferior",
    "tagRiftBurrwitchRoad": "Portal da Ribanceira Nebulosa",
    "tagRiftWightmire": "Portal de Wightmire",
    "tagRiftFloodedPassage": "Portal da Passagem Inundada",
    "tagRiftBurrwitchOutskirts": "Portal dos Arredores de Burrwitch",
    "tagRiftBurrwitchVillage": "Portal do Vilarejo de Burrwitch",
    "tagRiftWardensCellar": "Portal do Porão do Carcereiro",
    "tagRiftWardensLabratory01": "Portal da Passagem Subterrânea",
    "tagRiftWardensLabratory02": "Portal do Laboratório do Carcereiro",
    "tagRiftBrokenHills": "Portal das Colinas Partidas",
    "tagRiftOldArkovia": "Portal da Velha Arkóvia",
    "tagRiftArkovianFoothills": "Portal dos Sopés Arkovianos",
    "tagRiftCronleysHideout": "Portal do Esconderijo de Cronley",
    "tagRiftTwinFalls": "Portal das Cachoeiras Gêmeas",
    "tagRiftSmugglersPass": "Portal da Passagem do Contrabandista",
    "tagRiftSmugglersRoad": "Portal da Trilha do Garimpeiro",
    "tagRiftJaggedWaste": "Portal dos Sertões dos Pinheiros",
    "tagRiftDeadmansGulch": "Portal da Ravina do Morto",
    "tagRiftHomestead": "Portal da Herdade",
    "tagRiftRottedCroplands": "Portal das Terras Agrícolas Putrefatas",
    "tagRiftSorrowsBastion": "Portal do Bastião da Amargura",
    "tagRiftBloodGrove": "Portal do Bosque Sangrento",
    "tagRiftDarkvale": "Portal do Portão de Valescuro",
    "tagRiftAlpineGate": "Portal das Montanhas de Asterkarn",
    "tagRiftAlpineRoad": "Portal da Estrada de Asterkarn",
    "tagRiftAlpineValley": "Portal do Vale de Asterkarn",
    "tagRiftAlpineFort": "Portal do Forte Ikon",
    "tagRiftNecropolisGate": "Portal dos Portões da Necrópole",
    "tagRiftNecropolisInterior": "Portal da Necrópole Interior",
    "tagGDX1RiftGloomwaldEntrance": "Portal de Gloomwald",
    "tagGDX1RiftGloomwaldRiverCrossing": "Portal do Cruzamento de Gloomwald",
    "tagGDX1RiftUgdenbogCoven": "Portal do Refúgio da Seita",
    "tagGDX1RiftUgdenbogCenter": "Portal de Ugdenbog",
    "tagGDX1RiftUgdenbogVillage": "Portal de Barrowholm",
    "tagGDX1RiftMalmouthAetherfire": "Portal do Posto Isolado",
    "tagGDX1RiftMalmouthOutskirts": "Portal dos Arredores de Malmouth",
    "tagGDX1RiftMalmouthIndustrial": "Portal do Distrito do Aço de Malmouth",
    "tagGDX1RiftMalmouthInner": "Portal da Colina da Coroa de Malmouth",
    "tagGDX1RiftMalmouthSewers": "Portal dos Esgotos de Malmouth",
    "tagGDX2RiftWitchGodBase": "Portal do Conclave dos Três",
    "tagGDX2RiftKorvanPlateau": "Portal do Planalto de Korvan",
    "tagGDX2RiftTempleOfOsyr": "Portal do Templo de Osyr",
    "tagGDX2RiftKorvanSands": "Portal das Areias de Korvan",
    "tagGDX2RiftCairanDocks": "Portal das Docas de Cairan",
    "tagGDX2RiftOasis": "Portal do Oásis da Ruína do Sol",
    "tagGDX2RiftVanguard": "Portal da Vanguarda dos Três",
    "tagGDX2RiftAbyd": "Portal das Ruínas de Abyd",
    "tagGDX2RiftInfernalWastes": "Portal do Ermo Infernal",
    "tagGDX2RiftKorvanCity": "Portal da Cidade de Korvan",
    "tagGDX2RiftTemple": "Portal da Tumba do Sol Feérico",
    "tagGDX2RiftEldritch": "Portal do Portão Feérico",
    "tagGDX2RiftLostOasis": "Portal do Oásis Perdido"
  },
  it:{
    "tagRiftDevilsCrossing": "Portale ~ Crocevia del Diavolo",
    "tagRiftLowerCrossing": "Portale ~ Crocevia Basso",
    "tagRiftBurrwitchRoad": "Portale ~ Banco Nebbioso",
    "tagRiftWightmire": "Portale ~ Wightmire",
    "tagRiftFloodedPassage": "Portale ~ Passaggio Allagato",
    "tagRiftBurrwitchOutskirts": "Portale ~ Periferia di Burrwitch",
    "tagRiftBurrwitchVillage": "Portale ~ Villaggio di Burrwitch",
    "tagRiftWardensCellar": "Portale ~ Cantina del Direttore",
    "tagRiftWardensLabratory01": "Portale ~ Transito Sotterraneo",
    "tagRiftWardensLabratory02": "Portale ~ Laboratorio del Direttore",
    "tagRiftBrokenHills": "Portale ~ Colline Spezzate",
    "tagRiftOldArkovia": "Portale ~ Arkovia Vecchia",
    "tagRiftArkovianFoothills": "Portale ~ Pendici Arkoviane",
    "tagRiftCronleysHideout": "Portale ~ Nascondiglio di Cronley",
    "tagRiftTwinFalls": "Portale ~ Cascate Gemelle",
    "tagRiftSmugglersPass": "Portale ~ Passo del Trafficante",
    "tagRiftSmugglersRoad": "Portale ~ Sentiero del Prospettore",
    "tagRiftJaggedWaste": "Portale ~ Pineta Desolata",
    "tagRiftDeadmansGulch": "Portale ~ Burrone del Morto",
    "tagRiftHomestead": "Portale ~ Homestead",
    "tagRiftRottedCroplands": "Portale ~ Campi Marcescenti",
    "tagRiftSorrowsBastion": "Portale ~ Bastione del Dolore",
    "tagRiftBloodGrove": "Portale ~ Bosco Sanguigno",
    "tagRiftDarkvale": "Portale ~ Cancello di Vallescura",
    "tagRiftAlpineGate": "Portale ~ Montagne Asterkarn",
    "tagRiftAlpineRoad": "Portale ~ Strada Asterkarn",
    "tagRiftAlpineValley": "Portale ~ Valle Asterkarn",
    "tagRiftAlpineFort": "Portale ~ Forte Ikon",
    "tagRiftNecropolisGate": "Portale ~ Cancelli della Necropoli",
    "tagRiftNecropolisInterior": "Portale ~ Interno della Necropoli",
    "tagGDX1RiftGloomwaldEntrance": "Portale ~ Gloomwald",
    "tagGDX1RiftGloomwaldRiverCrossing": "Portale ~ Crocevia di Gloomwald",
    "tagGDX1RiftUgdenbogCoven": "Portale ~ Rifugio della Congrega",
    "tagGDX1RiftUgdenbogCenter": "Portale ~ Ugdenbog",
    "tagGDX1RiftUgdenbogVillage": "Portale ~ Barrowholm",
    "tagGDX1RiftMalmouthAetherfire": "Portale ~ Guardia Isolata",
    "tagGDX1RiftMalmouthOutskirts": "Portale ~ Periferia di Malmouth",
    "tagGDX1RiftMalmouthIndustrial": "Portale ~ Distretto di Steelcap di Malmouth",
    "tagGDX1RiftMalmouthInner": "Portale ~ Colle della Corona di Malmouth",
    "tagGDX1RiftMalmouthSewers": "Portale ~ Fogne di Malmouth",
    "tagGDX2RiftWitchGodBase": "Portale del Conclave dei Tre",
    "tagGDX2RiftKorvanPlateau": "Portale dell'Altopiano di Korvan",
    "tagGDX2RiftTempleOfOsyr": "Portale del Tempio di Osyr",
    "tagGDX2RiftKorvanSands": "Portale delle Sabbie di Korvan",
    "tagGDX2RiftCairanDocks": "Portale dei Moli di Cairan",
    "tagGDX2RiftOasis": "Portale dell'Oasi della Rovina del Sole",
    "tagGDX2RiftVanguard": "Portale dell'Avanguardia dei Tre",
    "tagGDX2RiftAbyd": "Portale delle Rovine di Abyd",
    "tagGDX2RiftInfernalWastes": "Portale delle Lande Infernali",
    "tagGDX2RiftKorvanCity": "Portale della Città di Korvan",
    "tagGDX2RiftTemple": "Portale della Tomba del Sole di Eldritch",
    "tagGDX2RiftEldritch": "Portale del Cancello di Eldritch",
    "tagGDX2RiftLostOasis": "Portale dell'Oasi Perduta"
  },

pl:{
  "tagRiftDevilsCrossing": "Szczelina w Diabelskiej Przełęczy",
  "tagRiftLowerCrossing": "Szczelina w Niższej Przełęczy",
  "tagRiftBurrwitchRoad": "Szczelina na drodze do Burrwitch",
  "tagRiftWightmire": "Szczelina na bagnach Wightmire",
  "tagRiftFloodedPassage": "Szczelina w Zatopionym Przejściu",
  "tagRiftBurrwitchOutskirts": "Szczelina na Przedmieściach Burrwitch",
  "tagRiftBurrwitchVillage": "Szczelina w Wiosce Burrwitch",
  "tagRiftWardensCellar": "Szczelina w Piwnicy Nadzorcy",
  "tagRiftWardensLabratory01": "Szczelina w Podziemnym Trakcie",
  "tagRiftWardensLabratory02": "Szczelina w Ukrytym Laboratorium",
  "tagRiftBrokenHills": "Szczelina przy Złamanych Wzgórzach",
  "tagRiftOldArkovia": "Szczelina Starej Arkovii",
  "tagRiftArkovianFoothills": "Szczelina na Arkoviańskich Wzgórzach",
  "tagRiftCronleysHideout": "Szczelina przy Kryjówce Cronleya",
  "tagRiftTwinFalls": "Szczelina przy Dwóch Wodospadach",
  "tagRiftSmugglersPass": "Szczelina na Ścieżce Przemytnika",
  "tagRiftSmugglersRoad": "Szczelina na Wysokim Przepuście",
  "tagRiftJaggedWaste": "Szczelina w Sosnowym Gaju",
  "tagRiftDeadmansGulch": "Szczelina w Kanionie Umarłych",
  "tagRiftHomestead": "Szczelina przy Gospodarstwach",
  "tagRiftRottedCroplands": "Szczelina przy Splugawionych Polach",
  "tagRiftSorrowsBastion": "Szczelina w Bastionie Smutku",
  "tagRiftBloodGrove": "Szczelina w Krwawym Lesie",
  "tagRiftDarkvale": "Szczelina przy Bramie Darkvale",
  "tagRiftAlpineGate": "Szczelina w Górach Asterkarn",
  "tagRiftAlpineRoad": "Szczelina na drodze przez Asterkarn",
  "tagRiftAlpineValley": "Szczelina w Dolinie Asterkarn",
  "tagRiftAlpineFort": "Szczelina w Fort Ikon",
  "tagRiftNecropolisGate": "Szczelina u Bram Necropolis",
  "tagRiftNecropolisInterior": "Szczelina we Wnętrzu Necropolis",
  "tagGDX1RiftGloomwaldEntrance": "Szczelina w Gloomwald",
  "tagGDX1RiftGloomwaldRiverCrossing": "Szczelina na Skrzyżowaniu w Gloomwald",
  "tagGDX1RiftUgdenbogCoven": "Szczelina w Azylu Sabatu",
  "tagGDX1RiftUgdenbogCenter": "Szczelina w Ugdenbog",
  "tagGDX1RiftUgdenbogVillage": "Szczelina w Barrowholm",
  "tagGDX1RiftMalmouthAetherfire": "Szczelina w Samotnej Straży",
  "tagGDX1RiftMalmouthOutskirts": "Szczelina na Peryferiach Malmouth",
  "tagGDX1RiftMalmouthIndustrial": "Szczelina w Dzielnicy Stalowej Pokrywy",
  "tagGDX1RiftMalmouthInner": "Szczelina w Koronie Wzgórz",
  "tagGDX1RiftMalmouthSewers": "Szczelina w Kanałach Malmouth",
  "tagGDX2RiftWitchGodBase": "Szczelina w Konklawe Trójcy",
  "tagGDX2RiftKorvanPlateau": "Szczelina na Płaskowyżu Korvan",
  "tagGDX2RiftTempleOfOsyr": "Szczelina w Świątyni Osyr",
  "tagGDX2RiftKorvanSands": "Szczelina w Piaskach Korvan",
  "tagGDX2RiftCairanDocks": "Szczelina w Dokach Cairan",
  "tagGDX2RiftOasis": "Szczelina w Oazie Sunbane",
  "tagGDX2RiftVanguard": "Szczelina w Strażnicy Trójcy",
  "tagGDX2RiftAbyd": "Szczelina w Ruinach Abyd",
  "tagGDX2RiftInfernalWastes": "Szczelina w Piekielnym Ugorze",
  "tagGDX2RiftKorvanCity": "Szczelina w Mieście Korvan",
  "tagGDX2RiftTemple": "Szczelina w Grobowcu Upiornego Słońca",
  "tagGDX2RiftEldritch": "Szczelina przy Upiornej Bramie",
  "tagGDX2RiftLostOasis": "Szczelina w Zaginionej Oazie",
},

  ru:{
      "tagRiftDevilsCrossing": "Разлом Перекрёстка Дьявола",
  "tagRiftLowerCrossing": "Разлом Нижнего Перекрёстка",
  "tagRiftBurrwitchRoad": "Разлом Туманных Низин",
  "tagRiftWightmire": "Разлом Болот Нечисти",
  "tagRiftFloodedPassage": "Разлом Затопленного Прохода",
  "tagRiftBurrwitchOutskirts": "Разлом Окраины Чертополоха",
  "tagRiftBurrwitchVillage": "Разлом Деревни Чертополох",
  "tagRiftWardensCellar": "Разлом Подвала Коменданта",
  "tagRiftWardensLabratory01": "Разлом Перехода Коменданта",
  "tagRiftWardensLabratory02": "Разлом Лаборатории Коменданта",
  "tagRiftBrokenHills": "Разлом Изломанных Холмов",
  "tagRiftOldArkovia": "Разлом Старой Арковии",
  "tagRiftArkovianFoothills": "Разлом Арковианских Предгорий",
  "tagRiftCronleysHideout": "Разлом Логова Кронли",
  "tagRiftTwinFalls": "Разлом Двойного Водопада",
  "tagRiftSmugglersPass": "Разлом Перевала Контрабандистов",
  "tagRiftSmugglersRoad": "Разлом Тропы Старателей",
  "tagRiftJaggedWaste": "Разлом Соснового Нагорья",
  "tagRiftDeadmansGulch": "Разлом Ущелья Мертвеца",
  "tagRiftHomestead": "Разлом Усадьбы",
  "tagRiftRottedCroplands": "Разлом Гниющих Угодий",
  "tagRiftSorrowsBastion": "Разлом Бастиона Скорби",
  "tagRiftBloodGrove": "Разлом Кровавой Рощи",
  "tagRiftDarkvale": "Разлом Врат Тёмной Долины",
  "tagRiftAlpineGate": "Разлом Астеркарнских гор",
  "tagRiftAlpineRoad": "Разлом Астеркарнской дороги",
  "tagRiftAlpineValley": "Разлом Астеркарнской долины",
  "tagRiftAlpineFort": "Разлом форта Икон",
  "tagRiftNecropolisGate": "Разлом врат Некрополиса",
  "tagRiftNecropolisInterior": "Разлом двора Некрополиса",
  "tagGDX1RiftGloomwaldEntrance": "Разлом Темнолесья",
  "tagGDX1RiftGloomwaldRiverCrossing": "Разлом развилки Темнолесья",
  "tagGDX1RiftUgdenbogCoven": "Разлом прибежища ковена",
  "tagGDX1RiftUgdenbogCenter": "Разлом Угденской топи",
  "tagGDX1RiftUgdenbogVillage": "Разлом Могильного кургана",
  "tagGDX1RiftMalmouthAetherfire": "Разлом одинокой башни",
  "tagGDX1RiftMalmouthOutskirts": "Разлом предместий Мальмута",
  "tagGDX1RiftMalmouthIndustrial": "Разлом Литейного квартала",
  "tagGDX1RiftMalmouthInner": "Разлом Венценосного холма",
  "tagGDX1RiftMalmouthSewers": "Разлом канализации Мальмута",
  "tagGDX2RiftWitchGodBase": "Разлом Конклава Троих",
  "tagGDX2RiftKorvanPlateau": "Разлом Корванского плато",
  "tagGDX2RiftTempleOfOsyr": "Разлом Храма Осира",
  "tagGDX2RiftKorvanSands": "Разлом Корванских песков",
  "tagGDX2RiftCairanDocks": "Разлом Кайранских доков",
  "tagGDX2RiftOasis": "Разлом Знойного оазиса",
  "tagGDX2RiftVanguard": "Разлом Авангарда Троих",
  "tagGDX2RiftAbyd": "Разлом Руин Абида",
  "tagGDX2RiftInfernalWastes": "Разлом Адских пустошей",
  "tagGDX2RiftKorvanCity": "Разлом Корвана",
  "tagGDX2RiftTemple": "Разлом Гробницы Жуткого Солнца",
  "tagGDX2RiftEldritch": "Разлом Жутких врат",
  "tagGDX2RiftLostOasis": "Разлом Затерянного оазиса"
  },
  zh:{
      "tagRiftDevilsCrossing": "恶魔十字传送门",
    "tagRiftLowerCrossing": "下游渡口传送门",
    "tagRiftBurrwitchRoad": "迷雾河畔传送门",
    "tagRiftWightmire": "尸妖泥沼传送门",
    "tagRiftFloodedPassage": "浸没通道传送门",
    "tagRiftBurrwitchOutskirts": "伯尔维治郊外传送门",
    "tagRiftBurrwitchVillage": "伯尔维治村传送门",
    "tagRiftWardensCellar": "典狱长的地下室传送门",
    "tagRiftWardensLabratory01": "地下通道传送门",
    "tagRiftWardensLabratory02": "典狱长的实验室传送门",
    "tagRiftBrokenHills": "破碎丘陵传送门",
    "tagRiftOldArkovia": "古安克维亚传送门",
    "tagRiftArkovianFoothills": "安克维亚山麓传送门",
    "tagRiftCronleysHideout": "克隆利的藏身处传送门",
    "tagRiftTwinFalls": "双子瀑布传送门",
    "tagRiftSmugglersPass": "走私者的通道传送门",
    "tagRiftSmugglersRoad": "采矿者小径传送门",
    "tagRiftJaggedWaste": "松林荒地传送门",
    "tagRiftDeadmansGulch": "亡者峡谷传送门",
    "tagRiftHomestead": "霍姆斯特德传送门",
    "tagRiftRottedCroplands": "腐坏田地传送门",
    "tagRiftSorrowsBastion": "悲伤城堡传送门",
    "tagRiftBloodGrove": "血森林传送门",
    "tagRiftDarkvale": "黑谷门传送门",
    "tagRiftAlpineGate": "阿斯特堪山脉传送门",
    "tagRiftAlpineRoad": "阿斯特堪之路传送门",
    "tagRiftAlpineValley": "阿斯特堪山谷传送门",
    "tagRiftAlpineFort": "圣像堡传送门",
    "tagRiftNecropolisGate": "大墓地传送门",
    "tagRiftNecropolisInterior": "大墓地内部传送门",
    "tagGDX1RiftGloomwaldEntrance": "幽暗森林传送门",
    "tagGDX1RiftGloomwaldRiverCrossing": "幽暗森林渡口传送门",
    "tagGDX1RiftUgdenbogCoven": "女巫团避难所传送门",
    "tagGDX1RiftUgdenbogCenter": "巫登沼泽传送门",
    "tagGDX1RiftUgdenbogVillage": "巴罗霍尔姆传送门",
    "tagGDX1RiftMalmouthAetherfire": "孤望塔传送门",
    "tagGDX1RiftMalmouthOutskirts": "马尔茅斯郊外传送门",
    "tagGDX1RiftMalmouthIndustrial": "马尔茅斯钢盖区传送门",
    "tagGDX1RiftMalmouthInner": "马尔茅斯皇冠高地传送门",
    "tagGDX1RiftMalmouthSewers": "马尔茅斯下水道传送门",
    "tagGDX2RiftWitchGodBase": "三巫神秘会传送门",
    "tagGDX2RiftKorvanPlateau": "科凡高原传送门",
    "tagGDX2RiftTempleOfOsyr": "奥西尔神庙传送门",
    "tagGDX2RiftKorvanSands": "科凡沙漠传送门",
    "tagGDX2RiftCairanDocks": "凯伦码头传送门",
    "tagGDX2RiftOasis": "炎阳绿洲传送门",
    "tagGDX2RiftVanguard": "三巫神先锋营传送门",
    "tagGDX2RiftAbyd": "阿贝德废墟传送门",
    "tagGDX2RiftInfernalWastes": "炼狱荒地传送门",
    "tagGDX2RiftKorvanCity": "科凡城传送门",
    "tagGDX2RiftTemple": "邪阳之墓传送门",
    "tagGDX2RiftEldritch": "邪术之门传送门",
    "tagGDX2RiftLostOasis": "迷失绿洲传送门"
  },
  de:{
    "tagRiftDevilsCrossing": "Rift in Devil's Crossing",
    "tagRiftLowerCrossing": "Rift in Lower Crossing",
    "tagRiftBurrwitchRoad": "Rift in der Foggy Bank",
    "tagRiftWightmire": "Rift in Wightmire",
    "tagRiftFloodedPassage": "Rift in der überfluteten Passage",
    "tagRiftBurrwitchOutskirts": "Rift in den Außenbezirken von Burrwitch",
    "tagRiftBurrwitchVillage": "Rift in Dorf Burrwitch",
    "tagRiftWardensCellar": "Rift im Keller des Aufsehers",
    "tagRiftWardensLabratory01": "Rift im Untergrunddurchgang",
    "tagRiftWardensLabratory02": "Rift im Labor des Aufsehers",
    "tagRiftBrokenHills": "Rift in den Broken Hills",
    "tagRiftOldArkovia": "Rift in Old Arkovia",
    "tagRiftArkovianFoothills": "Rift in den Arkovian Foothills",
    "tagRiftCronleysHideout": "Rift in Cronleys Versteck",
    "tagRiftTwinFalls": "Rift in Twin Falls",
    "tagRiftSmugglersPass": "Rift im Schmugglerpass",
    "tagRiftSmugglersRoad": "Rift am Prospector's Trail",
    "tagRiftJaggedWaste": "Rift in der Kiefernwildnis",
    "tagRiftDeadmansGulch": "Rift in der Totenschlucht",
    "tagRiftHomestead": "Rift in Homestead",
    "tagRiftRottedCroplands": "Rift im faulenden Ackerland",
    "tagRiftSorrowsBastion": "Rift in Sorrow's Bastion",
    "tagRiftBloodGrove": "Rift im Blood Grove",
    "tagRiftDarkvale": "Rift in Darkvale Gate",
    "tagRiftAlpineGate": "Rift in den Asterkarn-Bergen",
    "tagRiftAlpineRoad": "Rift auf der Asterkarnstraße",
    "tagRiftAlpineValley": "Rift im Asterkarntal",
    "tagRiftAlpineFort": "Rift in Fort Ikon",
    "tagRiftNecropolisGate": "Rift bei den Toren der Nekropolis",
    "tagRiftNecropolisInterior": "Rift im Innenbereich der Nekropolis",
    "tagGDX1RiftGloomwaldEntrance": "Rift in Gloomwald",
    "tagGDX1RiftGloomwaldRiverCrossing": "Rift in Gloomwald Crossing",
    "tagGDX1RiftUgdenbogCoven": "Rift im Unterschlupf des Hexenzirkels",
    "tagGDX1RiftUgdenbogCenter": "Rift in Ugdenbog",
    "tagGDX1RiftUgdenbogVillage": "Rift in Barrowholm",
    "tagGDX1RiftMalmouthAetherfire": "Rift in der Einsamen Wache",
    "tagGDX1RiftMalmouthOutskirts": "Rift in den Außenbezirken von Malmouth",
    "tagGDX1RiftMalmouthIndustrial": "Rift im Malmouth-Stahlkappenviertel",
    "tagGDX1RiftMalmouthInner": "Rift im Malmouth-Kronenhügel",
    "tagGDX1RiftMalmouthSewers": "Rift in der Kanalisation von Malmouth",
    "tagGDX2RiftWitchGodBase": "Rift im Konklave der Drei",
    "tagGDX2RiftKorvanPlateau": "Rift im Korvanischen Plateau",
    "tagGDX2RiftTempleOfOsyr": "Rift im Tempel von Osyr",
    "tagGDX2RiftKorvanSands": "Rift in der Korvanischen Wüste",
    "tagGDX2RiftCairanDocks": "Rift in den Docks von Cairan",
    "tagGDX2RiftOasis": "Rift in der Sonnenbann-Oase",
    "tagGDX2RiftVanguard": "Rift bei der Vorhut der Drei",
    "tagGDX2RiftAbyd": "Rift in den Ruinen von Abyd",
    "tagGDX2RiftInfernalWastes": "Rift im Höllischen Ödland",
    "tagGDX2RiftKorvanCity": "Rift in Korvan Stadt",
    "tagGDX2RiftTemple": "Rift im Grab der Übernatürlichen Sonne",
    "tagGDX2RiftEldritch": "Rift am Übernatürlichen Tor",
    "tagGDX2RiftLostOasis": "Rift in der Verschollenen Oase"
  },
  ja:{
    "tagRiftDevilsCrossing": "デビルズ クロッシング リフト",
    "tagRiftLowerCrossing": "ローワー クロッシング リフト",
    "tagRiftBurrwitchRoad": "霧の土手 リフト",
    "tagRiftWightmire": "ワイトマイア リフト",
    "tagRiftFloodedPassage": "冠水通路 リフト",
    "tagRiftBurrwitchOutskirts": "バーウィッチ 郊外 リフト",
    "tagRiftBurrwitchVillage": "バーウィッチ村 リフト",
    "tagRiftWardensCellar": "ウォードンの地下室 リフト",
    "tagRiftWardensLabratory01": "地下搬送施設 リフト",
    "tagRiftWardensLabratory02": "ウォードンの実験室 リフト",

    "tagRiftBrokenHills": "ブロークン ヒルズ リフト",
    "tagRiftOldArkovia": "オールド アーコヴィア リフト",
    "tagRiftArkovianFoothills": "アーコヴィア丘陵 リフト",
    "tagRiftCronleysHideout": "クロンリーの隠れ家 リフト",
    "tagRiftTwinFalls": "双子滝 リフト",
    "tagRiftSmugglersPass": "密輸人の道 リフト",
    "tagRiftSmugglersRoad": "探鉱者の道 リフト",
    "tagRiftJaggedWaste": "松荒原 リフト",
    "tagRiftDeadmansGulch": "デッドマン峡谷 リフト",

    "tagRiftHomestead": "ホームステッド リフト",
    "tagRiftRottedCroplands": "腐敗農地 リフト",
    "tagRiftSorrowsBastion": "悲嘆の砦 リフト",
    "tagRiftBloodGrove": "血の森 リフト",
    "tagRiftDarkvale": "ダークヴェイル ゲート リフト",
    "tagRiftAlpineGate": "アスターカーン山地 リフト",
    "tagRiftAlpineRoad": "アスターカーン街道 リフト",
    "tagRiftAlpineValley": "アスターカーン渓谷 リフト",
    "tagRiftAlpineFort": "アイコン砦 リフト",
    "tagRiftNecropolisGate": "ネクロポリスの門 リフト",
    "tagRiftNecropolisInterior": "ネクロポリス内部 リフト",

    "tagGDX1RiftGloomwaldEntrance": "グルームヴァルト リフト",
    "tagGDX1RiftGloomwaldRiverCrossing": "グルームヴァルト クロッシング リフト",
    "tagGDX1RiftUgdenbogCoven": "魔女団の避難所 リフト",
    "tagGDX1RiftUgdenbogCenter": "ウグデンボーグ リフト",
    "tagGDX1RiftUgdenbogVillage": "バロウホルム リフト",
    "tagGDX1RiftMalmouthAetherfire": "ローン ウォッチ リフト",
    "tagGDX1RiftMalmouthOutskirts": "マルマス郊外 リフト",
    "tagGDX1RiftMalmouthIndustrial": "マルマス スチールキャップ地区 リフト",
    "tagGDX1RiftMalmouthInner": "マルマス クラウン ヒル リフト",
    "tagGDX1RiftMalmouthSewers": "マルマス下水道 リフト",

    "tagGDX2RiftWitchGodBase": "三神の秘密会議所 リフト",
    "tagGDX2RiftKorvanPlateau": "コルヴァン高原 リフト",
    "tagGDX2RiftTempleOfOsyr": "オシール寺院 リフト",
    "tagGDX2RiftKorvanSands": "コルヴァン砂漠 リフト",
    "tagGDX2RiftCairanDocks": "カイラン埠頭 リフト",
    "tagGDX2RiftOasis": "炎陽オアシス リフト",
    "tagGDX2RiftVanguard": "三神の前衛 リフト",
    "tagGDX2RiftAbyd": "アビド遺跡 リフト",
    "tagGDX2RiftInfernalWastes": "地獄の荒地 リフト",
    "tagGDX2RiftKorvanCity": "コルヴァン市 リフト",
    "tagGDX2RiftTemple": "エルドリッチの太陽の墓 リフト",
    "tagGDX2RiftEldritch": "エルドリッチの門 リフト",
    "tagGDX2RiftLostOasis": "失われたオアシス リフト"
  },
  ko:{
    "tagRiftDevilsCrossing": "데블스 크로싱 리프트",
    "tagRiftLowerCrossing": "로워 크로싱 리프트",
    "tagRiftBurrwitchRoad": "안개낀 강기슭 리프트",
    "tagRiftWightmire": "유령늪 리프트",
    "tagRiftFloodedPassage": "침수된 통로 리프트",
    "tagRiftBurrwitchOutskirts": "버위치 외곽 리프트",
    "tagRiftBurrwitchVillage": "버위치 마을 리프트",
    "tagRiftWardensCellar": "교도소장의 지하실 리프트",
    "tagRiftWardensLabratory01": "지하 운송로 리프트",
    "tagRiftWardensLabratory02": "교도소장의 실험실 리프트",

    "tagRiftBrokenHills": "브로큰 힐스 리프트",
    "tagRiftOldArkovia": "옛 아코비아 리프트",
    "tagRiftArkovianFoothills": "아코비아 구릉지 리프트",
    "tagRiftCronleysHideout": "크론리의 은신처 리프트",
    "tagRiftTwinFalls": "쌍둥이 폭포 리프트",
    "tagRiftSmugglersPass": "밀수업자의 통로 리프트",
    "tagRiftSmugglersRoad": "채굴자의 흔적 리프트",
    "tagRiftJaggedWaste": "관목림 지대 리프트",
    "tagRiftDeadmansGulch": "죽은 자의 협곡 리프트",

    "tagRiftHomestead": "홈스테드 리프트",
    "tagRiftRottedCroplands": "썩어가는 경작지 리프트",
    "tagRiftSorrowsBastion": "슬픔의 요새 리프트",
    "tagRiftBloodGrove": "핏빛 숲 리프트",
    "tagRiftDarkvale": "다크베일 관문 리프트",
    "tagRiftAlpineGate": "아스테르칸 산맥 리프트",
    "tagRiftAlpineRoad": "아스테르칸 통행로 리프트",
    "tagRiftAlpineValley": "아스테르칸 계곡 리프트",
    "tagRiftAlpineFort": "아이컨 요새 리프트",
    "tagRiftNecropolisGate": "네크로폴리스 입구 리프트",
    "tagRiftNecropolisInterior": "네크로폴리스 내부 리프트",

    "tagGDX1RiftGloomwaldEntrance": "어둠숲 리프트",
    "tagGDX1RiftGloomwaldRiverCrossing": "어둠숲 갈림길 리프트",
    "tagGDX1RiftUgdenbogCoven": "마녀단의 피신처 리프트",
    "tagGDX1RiftUgdenbogCenter": "우그덴늪 리프트",
    "tagGDX1RiftUgdenbogVillage": "바로우홀름 리프트",
    "tagGDX1RiftMalmouthAetherfire": "외로운 망루 리프트",
    "tagGDX1RiftMalmouthOutskirts": "말무스 외곽 리프트",
    "tagGDX1RiftMalmouthIndustrial": "말무스 강철지붕 지구 리프트",
    "tagGDX1RiftMalmouthInner": "말무스 왕관 언덕 리프트",
    "tagGDX1RiftMalmouthSewers": "말무스 하수도 리프트",

    "tagGDX2RiftWitchGodBase": "삼신의 비밀회의장 리프트",
    "tagGDX2RiftKorvanPlateau": "코르반 고원 리프트",
    "tagGDX2RiftTempleOfOsyr": "오시르 사원 리프트",
    "tagGDX2RiftKorvanSands": "코르반 사막 리프트",
    "tagGDX2RiftCairanDocks": "카이란 항구 리프트",
    "tagGDX2RiftOasis": "선베인 오아시스 리프트",
    "tagGDX2RiftVanguard": "삼신의 전초기지 리프트",
    "tagGDX2RiftAbyd": "아비드 폐허 리프트",
    "tagGDX2RiftInfernalWastes": "지옥불 황무지 리프트",
    "tagGDX2RiftKorvanCity": "코르반 시 리프트",
    "tagGDX2RiftTemple": "엘드리치 태양의 무덤 리프트",
    "tagGDX2RiftEldritch": "엘드리치 관문 리프트",
    "tagGDX2RiftLostOasis": "잃어버린 오아시스 리프트",
  }
};



window.getRiftLabel = function(tag, fallback) {

  const langCode = (window.GDMMLang && GDMMLang.getLang && GDMMLang.getLang()) || 'en';
  const dict = window.RIFT_LABELS[langCode] || window.RIFT_LABELS.en || {};
  return dict[tag] || fallback || tag;
};

// Map des rifts par taille d'image (w x h)
window.RIFT_MARKERS_BY_SIZE = {
  '8948x9133': window.RIFT_MARKERS_CAIRN,
  '5142x3574': window.RIFT_MARKERS_MALMOUTH,
  '5427x5553': window.RIFT_MARKERS_KORVAN,
};
